### ISSUE TITLE
basis_get_bytes_per_block returns wrong values for uncompressed formats

### ISSUE THREAD

**Issue by MarkCallow** [BinomialLLC/basis_universal#101]
Here's a snippet of the code;

```
case transcoder_texture_format::cTFRGBA32:
	return sizeof(uint32_t) * 16;
case transcoder_texture_format::cTFRGB565:
case transcoder_texture_format::cTFBGR565:
case transcoder_texture_format::cTFRGBA4444:
	return sizeof(uint16_t) * 16;
```

The `* 16` is bogus. The reason this is apparently not causing any problems is because `lowlevel_transcoder::transcode_slice` ignores its `output_block_or_pixel_stride` parameter, which was set from the output of the subject function, for all of the uncompressed formats, using instead sizeof(uint32_t) or sizeof(uint16_t).

**Comment by richgel999** [comment]
Hi Mark - Yea, we have a naming convention issue. This is confusing.

basis_get_bytes_per_block() always returns how large a block needs to be for each format. For the uncompressed formats, it returns the total block size, not the texel size.

However, the output_block_or_pixel_stride_in_bytes parameter is blocks for compressed formats, and pixels/texels for the uncompressed formats. The user needs to divide the output from basis_get_bytes_per_block() by 16 for the uncompressed formats to pass in the correct value to transcode_slice(). I'll fix this.

**Comment by richgel999** [comment]
Fixed in UASTC build coming today.
