### ISSUE TITLE
block artifacts remains for certain image, even set -endpoint_rdo_thresh 1

### ISSUE THREAD

**Issue by goldenyz** [BinomialLLC/basis_universal#103]
Hi, we are trying to use '.basis' as our basic texture file format. But we found that there are some block artifacts for certain images:
original:
![ldr-rgb-00-s](https://user-images.githubusercontent.com/8434711/72789303-81cd3580-3c6e-11ea-9dcb-449cd5cd76ad.png)
unpacked (ETC1_RGB):
![ldr-rgb-00-s-m-e-100_unpacked_rgb_ETC1_RGB_0000](https://user-images.githubusercontent.com/8434711/72789488-d8d30a80-3c6e-11ea-843f-03afe803ca38.png)

original:
![ldr-rgb-03](https://user-images.githubusercontent.com/8434711/72789636-159f0180-3c6f-11ea-9622-64a6b9ff53b7.png)
unpacked (ETC1_RGB):
![ldr-rgb-03_unpacked_rgb_ETC1_RGB_0000](https://user-images.githubusercontent.com/8434711/72789710-323b3980-3c6f-11ea-9b69-11be7d46bbfe.png)

command used:
```bash
./basisu ldr-rgb-03.png -comp_level 4 -max_selectors 16128 -max_endpoints 16128 -endpoint_rdo_thresh 1
```
could anyone help to find out why?

**Comment by slimbuck** [comment]
Try setting the quality level to maximum using argument "-q 255". This has the biggest effect on resulting image quality.

**Comment by goldenyz** [comment]
> Try setting the quality level to maximum using argument "-q 255". This has the biggest effect on resulting image quality.

I have tried the argument. But the block artifacts remains

**Comment by slimbuck** [comment]
Hi @goldenyz,
Yes I see. The compressed version of this image seems to have very nasty block compression artifacts. I'm sure @richgel999 could shed some light on why that is, but for what it's worth most color images I have tried have far fewer artifacts than you are getting here.

**Comment by goldenyz** [comment]
> Hi @goldenyz,
> Yes I see. The compressed version of this image seems to have very nasty block compression artifacts. I'm sure @richgel999 could shed some light on why that is, but for what it's worth most color images I have tried have far fewer artifacts than you are getting here.

Yes, the compressed version for most color images are acceptable. But in production,  we may need a measurement for the acceptability. If the compressed image aren't acceptable, we can degrade into the original image... Do you have any methods for the measurement? It would be helpful for us, too.

**Comment by slimbuck** [comment]
Hi @goldenyz,

basisu supports the -stats flag which will output image quality metrics. Perhaps you could use that?

(I haven't used stats much myself).

**Comment by richgel999** [comment]
These look like typical ETC1S block artifacts. We only get 1 base color per 4x4 pixel block, and if there are large chroma transitions then block artifacts can show up. (Regular ETC1 has this issue too, except it occurs on 4x2 or 2x4 block boundaries.)

We're adding a HQ mode to Basis Universal within weeks, which will address this issue. Although the bitrate is going to be a lot higher (but go down over time).

One thing that helps with this is to enlarge your texture with filtering.

(I'll grab your image in a bit and encode it myself.)

**Comment by richgel999** [comment]
Even BC1 is having block artifact problems with this texture - I recommend you enlarge it by 2x with a filtering in Photoshop/PSP/etc. and try encoding it again:

![unpacked_bc1](https://user-images.githubusercontent.com/6934809/73498604-c0a86d00-438b-11ea-9362-16162833cddf.png)

This was packed to BC1 using stb_dxt STB_DXT_HIGHQUAL.

**Comment by goldenyz** [comment]
@richgel999 Looking forward to the HQ mode. I have tried the encoding with ASTC 4*4 with medium in PVRTexTool, And the result seems acceptable:
![image](https://user-images.githubusercontent.com/8434711/73511976-bb4a3180-4422-11ea-8065-ecc096ba0555.png)


> Even BC1 is having block artifact problems with this texture - I recommend you enlarge it by 2x with filtering in Photoshop/PSP/etc. and try encoding it again:
> 
> ![unpacked_bc1_01](https://user-images.githubusercontent.com/6934809/73498676-f51c2900-438b-11ea-9bf2-7e84d7ffa189.png)
> 
> This was packed to BC1 using stb_dxt STB_DXT_HIGHQUAL.

Does this image is the result of enlarged 2x?

**Comment by richgel999** [comment]
The UASTC build coming today fixes this - I highly recommend you give it a try once it's released. You can use uastc on problematic textures, and ETC1S on the others.
