### ISSUE TITLE
Compression does not use all cores on multi-core CPU

### ISSUE THREAD

**Issue by hjlld** [BinomialLLC/basis_universal#108]
I am trying to compress a video texture on my Xeon server, but not all cores are used, usually one to three cores are working, and some time CPU usage drops to zero.

It's not so much fast as my imagination.

command line:
```
./basisu.exe -tex_type video -framerate 20 -multifile_printf "./F1/noAlpha/F10%03u.png" -multifile_first 0 -multifile_num 360 -no_alpha -level 5
```

Xeon server detail:
CPU:  Intel(R) Xeon(R) Gold 5118 CPU x2
RAM： 192GB
GPU: NVIDIA Tesla V100-PCIE-16GB x2

![20200224162848](https://user-images.githubusercontent.com/11457246/75137761-6b117700-5723-11ea-9c70-736dca614b50.png)

**Comment by richgel999** [comment]
Hmm - We use "std::thread::hardware_concurrency()" to query the # of HW threads (in compress_mode() basisu_tool.cpp). 

There are some single threaded sections in the code - perhaps you are seeing those? There are also a lot of multithreaded portions too.

**Comment by richgel999** [comment]
Can you let it go an watch the core utilization over time?

**Comment by hjlld** [comment]
I over watched the whole progress, and i'm sure this happens with video texture compression, there's no problem for image texture.

**Comment by richgel999** [comment]
We will be improving this over time. (Remember, it is a texture codec first, texture video codec second.)

**Comment by hjlld** [comment]
Thank you, then i close this issue.
