### ISSUE TITLE
Basic implementation

### ISSUE THREAD

**Issue by Leadwerks** [BinomialLLC/basis_universal#109]
I'm attempting to work this library into our art pipeline. Here is my code so far:
```
void* SavePixmap(int width, int height, int format, void* pixels, uint64_t size, wchar_t* extension, uint64_t& returnsize)
{
	if (format != VK_FORMAT_R8G8B8A8_UNORM) return nullptr;
	if (wstring(extension) != L"basisu") return nullptr;

	image img = image(width,height);
	char* thing = (char*)pixels;
	img.set_all(basisu::color_rgba(*thing));

	basis_compressor_params params;
	params.m_source_images.push_back(img);
	params.m_mip_gen = true;
	params.m_check_for_alpha = true;
	basist::etc1_global_selector_codebook sel_codebook(basist::g_global_selector_cb_size, basist::g_global_selector_cb);
	params.m_pSel_codebook = &sel_codebook;
	
	basis_compressor c;
	if (!c.init(params))
	{
		error_printf("basis_compressor::init() failed!\n");
		return nullptr;
	}

	basis_compressor::error_code ec = c.process();
```
It seems pretty straightforward, but I am receiving the error "cECFailedFrontEnd". Is there something else I have to set? Am I missing something? Thanks.

**Comment by Leadwerks** [comment]
Here is the printed output:

> basis_compressor::basis_compressor
> basis_compressor::init
> basis_compressor::process
> basis_compressor::read_source_images
> Source image index 0 filename  2048x2048 has alpha: 0
> Any source image has alpha: 0
> ****** Slice 0: mip 0, alpha_slice: 0, filename: "", original: 2048x2048 actual: 2048x2048
> Total blocks: 262144, Total macroblocks: 65536
> Total basis file slices: 1
> Slice: 0, alpha: 0, orig width/height: 2048x2048, width/height: 2048x2048, first_block: 0, image_index: 0, mip_level: 0, iframe: 0
> basis_compressor::validate_texture_type_constraints
> basis_compressor::process_frontend
> basisu_frontend::init: Multithreaded: 1, NumEndpointClusters: 0, NumSelectorClusters: 0, Perceptual: 1, CompressionLevel: 1
> Global sel codebook pal bits: 0, Global sel codebook mod bits: 0, Use hybrid selector codebook: 0, Hybrid codebook quality thresh: 0.000000
> ERROR: basisu_frontend::init() failed!
> ERROR: Compressor frontend stage failed!

**Comment by Leadwerks** [comment]
Here are the bits I was missing. Maybe it will help someone else:
```
	image img = image(width, height);
	char* thing = (char*)pixels;
	img.set_all(basisu::color_rgba(*thing));

	basis_compressor_params params;
	params.m_source_images.push_back(img);
	params.m_mip_gen = 0;// true;
	params.m_check_for_alpha = true;
	params.m_quality_level = 128;
	
	params.m_multithreading = true;
	int num_threads = std::thread::hardware_concurrency();
	if (num_threads < 1) num_threads = 1;
	job_pool jpool(num_threads);
	params.m_pJob_pool = &jpool;

	basist::etc1_global_selector_codebook sel_codebook(basist::g_global_selector_cb_size, basist::g_global_selector_cb);
	params.m_pSel_codebook = &sel_codebook;

	basis_compressor c;

	if (!c.init(params))
	{
		error_printf("basis_compressor::init() failed!\n");
		return nullptr;
	}
```

**Comment by metaphore** [comment]
So pretty much you only needed to set these two properties on top of what you had
```
params.m_quality_level
params.m_pJob_pool
```
A good note though, thanks for posting it!
