### ISSUE TITLE
basis_compressor::get_basis_file()

### ISSUE THREAD

**Issue by Leadwerks** [BinomialLLC/basis_universal#110]
I suggest adding the following method to the class:

**basis_file&`basis_compressor::get_basis_file()**

I'm using this to compress and save .basis files in our own file system. Maybe save-to-memory is already in there somewhere, but I didn't see it.

**Comment by richgel999** [comment]
Sure, we can add this.

There is basis_compressor::get_output_basis_file(), which returns a std::vector<uint8_t> that contains the entire .basis file in a blob in memory. You could then cast this as needed.

**Comment by Leadwerks** [comment]
That works just as well, thanks.
