### ISSUE TITLE
color changed when encode to basis

### ISSUE THREAD

**Issue by goldenyz** [BinomialLLC/basis_universal#111]
Hi, guys. I have encounter an issue when encode this image:
![model8](https://user-images.githubusercontent.com/8434711/75974689-31eeb900-5f12-11ea-8802-c1ade9dc9aac.png)
The output image is:
![model8](https://user-images.githubusercontent.com/8434711/75974728-42069880-5f12-11ea-89d0-6115e2e9269e.png)
The color changed a lot...

The command line I use to encode is as follows:
```bash
basisu -file ***.png -q 255  -mipmap -y_flip
```
I have tried:
```bash
basisu -file ***.png -mipmap -y_flip -max_endpoints 16128 -max_selectors 16128 -no_selector_rdo -no_endpoint_rdo
```
But nothing changed....

**Comment by goldenyz** [comment]
I have tried the a pure image, but the color is changed too...
![model8_512](https://user-images.githubusercontent.com/8434711/75983582-c1509800-5f23-11ea-9250-d882cc17effc.png)
The encoded image is shown as follows:
![model8_512](https://user-images.githubusercontent.com/8434711/75983631-d2010e00-5f23-11ea-8c8e-79cf21835b43.png)

**Comment by richgel999** [comment]
This slight color shift is because the internal ETC1S texture format only has 555 base colors on each block. The system does its best to minimize the error, but it's not perfect.

UASTC mode, which is coming today, will fix this. But the files are larger. So it's a tradeoff.

**Comment by richgel999** [comment]
The original color (of your all-solid image) is: 193,189,185
The transcoded color: 196, 188,188

The delta is +3, -1, +3. This is definitely due to ETC1S, or transcoder quantization. Can you play with the source image a little bit (modifying the RGB values *slightly*), to see if you can force the system to "snap" into different quantization bins that look better for your application? (Or you can wait for UASTC, and just use that on problematic textures.)

**Comment by goldenyz** [comment]
@richgel999 Thanks richgel999, looking forward to the UASTC mode. We use the basis for Web on Windows and Mac, which is not support ASTC natively when rendering. If we transcode basis to ETC/BC1/PVRTC, the color shift will occur. So the only option for us is to find some way to filter out the "pure color" images (it seems that the color shift of these images are sensitive for eyes) and switch to the original one...
