### ISSUE TITLE
Compute shader support?

### ISSUE THREAD

**Issue by nh2** [BinomialLLC/basis_universal#120]
In https://richg42.blogspot.com/2020/01/uastc-block-format-encoding.html you describe that

> Transcoding can either be done using the CPU or with a GPU compute shader.

Is a compute shader (especially for use with WebGL) already in the making, or planned?

I imagine this might significantly reduce CPU usage on mobile devices.

Thanks!

**Comment by richgel999** [comment]
UASTC transcoding can be done using either compute or SIMD/SPMD. Most likely we'll have an ispc implementation available before compute.

**Comment by expenses** [comment]
Does anyone know of a compute/fragment shader transcoder implementation? The wasm transcoder is too slow for my needs, so I want to look into getting a GPU transcoder working in wasm.
