### ISSUE TITLE
Mac builds

### ISSUE THREAD

**Issue by mrdoob** [BinomialLLC/basis_universal#123]
Any chance you could include the mac build in the [releases section](https://github.com/BinomialLLC/basis_universal/releases/tag/v1.12)?

https://github.com/feiss/basisu_macos_binary/blob/master/basisu

**Comment by richgel999** [comment]
Sure - I'll update it later today or tomorrow.

**Comment by richgel999** [comment]
Whoops - Apologies this fell between the cracks! I'll grab my Macbook and make builds tomorrow. Promise!

**Comment by UebelAndre** [comment]
Hello, friendly ping on this GitHub issue 😄

**Comment by ivnnv** [comment]
@richgel999 hi! :P

**Comment by vujadin** [comment]
tomorrow maybe?!  :P

**Comment by UebelAndre** [comment]
While it's not the same as having something included with a release, mac builds are now generated in CI.

From e486ceb66cebfd4a583a7df3a7c3bb54aa1c24b0: https://ci.appveyor.com/project/BinomialLLC/basis-universal/builds/35629622/job/r25gbq60xil76rwx/artifacts

**Comment by krupitskas** [comment]
@richgel999 I can help you setup github actions workflow to automate all the builds on main branch push, so it's always wil be up to day, is it a solution? :)

**Comment by atteneder** [comment]
It would be cool if the CI created a universal executable (supporting both Intel and Apple Silicon/ARM CPUs).

I just built that successfully, but found out:

SSE support is set at configuration time, which makes it impossible to have universal macOS builds supporting Intel+SSE and Apple Silicon (arm build fails trying to compile SSE). Detecting (or disabling) SSE at compile time would be better. I guess it's a rather exotic wish, but I still wanted to mention it. Disabling SSE for now would work as makeshift solution.

**Comment by zeux** [comment]
Since macOS binaries are now generated in CI, would it be possible to distribute them as part of the release archive? This would make it easier for other tools to recommend the use of basisu command line, since the users wouldn't need to build or figure out how to download them.
