### ISSUE TITLE
What does "occur in sRGB space" mean?

### ISSUE THREAD

**Issue by MarkCallow** [BinomialLLC/basis_universal#129]
What does the following quote from `basisu` help mean?

> By default, mipmap filtering will occur in sRGB space (for the RGB color channels) unless -linear is specified. You can override this behavior with -mip_srgb/-mip_linear.

Does this mean filtering is done without any decoding so if the data is sRGB, it will be filtered incorrectly and if it is linear it will be filtered correctly. Conversely if -linear is specified will sRGB data be filtered correctly because it is decoded to linear and linear filtered incorrectly because it is erroneously decoded as if it was sRGB?

To be clear for correct results filtering should always be done in a linear space.

**Comment by richgel999** [comment]
This is badly worded - I'll fix it. If the input is sRGB, image_resample() will convert the texture data to linear light first, do the filtering there, then convert back to sRGB. 

If the input is linear, nothing happens (it just filters the texture data).
