### ISSUE TITLE
Abort at line 1259 in basisu_uastc_enc.cpp

### ISSUE THREAD

**Issue by MarkCallow** [BinomialLLC/basis_universal#130]
The attached file when used as `basisu -uastc posy.jpg` causes an abort at lin 1259 in basisu_uastc_enc.cpp.

![negy](https://user-images.githubusercontent.com/2244683/78839640-bb7c2580-79ad-11ea-9baf-fe94654daf55.jpg)

**Comment by richgel999** [comment]
Thanks, I reproduced it. It was an invalid/unnecessary assert. I've checked in the fix (which is removing the assert).
