### ISSUE TITLE
Image loading irritants. 

### ISSUE THREAD

**Issue by SpehleonLP** [BinomialLLC/basis_universal#138]
I just started using this library so sorry if this has come up before; i don't really know my way around it well enough to start fixing it but this is a simple request...

In image loading, it really bothers me that when loading a bitmap or jpeg the dimensions are ints, but as a png they're uints; similarly the bitmap has it's own free memory function and the jpeg and png don't.   I should be able to declare a function pointer type and have it be compatible with all the load image functions IMO... 

I also think that the image reading functions should take a function pointer for an allocate function, its not good that if i want to manipulate the image a bit before compressing it i need to load it and then copy it into an image instead of just loading it directly into an image.  And having it take a memory allocating function would fix this. 

I'm also unsure of why the basisu::image::init function sets a background color if that just gets overwritten anyway.

**Comment by richgel999** [comment]
Please note that BasisU is not an image loading library. The encoder is a command line tool, technically not a library (yet). Once it is a library we will not be exposing any plain image reading functionality as part of the public API (that's a small nightmare). All image loading functionality will remain private, for internal use. I would have rather used something like stb_image, but it's not fuzz safe so we can't use it.

I'm not sure what you mean by an inconsistent interface. It's pretty simple and consistent, but remember this is internal functionality we will never expose to the end user so it doesn't matter:

![image](https://user-images.githubusercontent.com/6934809/81134300-4e16d280-8f22-11ea-8747-d78b262f1702.png)

As for the image::init() method, our goal is deterministic and reliably execution first, performance second. A memset() or equivalent executes at many GB/sec. on even ancient laptops. It's a non-issue. We can afford to clear our bitmaps. :-)
