### ISSUE TITLE
stdlib in transcoder

### ISSUE THREAD

**Issue by kg** [BinomialLLC/basis_universal#14]
Would you accept a pull request that replaces ```<vector>``` with stripped down non-stdlib code? Needing to link in the C++ standard library to decode basis files is kind of unfortunate

**Comment by richgel999** [comment]
Yup, std::vector sucks. I used it because of time constraints. If you've got an alternative that has similar semantics to std::vector, we'll get it in. 
Thanks,
-Rich

**Comment by JCash** [comment]
I support this request wholeheartedly @kg. Support burden with ABI differences for stdlib is something I (we) take very seriously, so we just have to avoid such libraries (which is a shame).

Have you already started with this work, and do you need help? If so, I'm willing to do so.

**Comment by kg** [comment]
I haven't started because I found no straightforward C vector implementations I felt safe dropping in. I'd have to build it from scratch which is a little riskier :)

**Comment by richgel999** [comment]
That's cool - we have a major transcoder update on the way very soon! Getting rid of std::vector would be nice.

**Comment by JCash** [comment]
The time has come for where I'm going to start using this library. And as I mentioned, I'd like to try to replace the stdlib dependencies.

I'm thinking of a C++ version of a vector class as a first step (porting to C is a different endeavour), for the decoder (as a first step). If anyone else has already started doing this, please let me know :)

**Comment by richgel999** [comment]
The std::vector usage has been replaced already. We also replaced std hash table used in the encoder (mostly). I'm going to close this for now, but feel free to open if you see any issues/improvements. Thanks!
