### ISSUE TITLE
basis_compressor uses transcoders without checking if they are supported

### ISSUE THREAD

**Issue by MarkCallow** [BinomialLLC/basis_universal#140]
This leads to an assert at /transcoder/basisu_transcoder.cpp,8313,transcode_slice when I have compiled to .wasm for which I omit bc7 support.

**Comment by richgel999** [comment]
Are you compiling the encoder to wasm? The encoder currently assumes all transcoders are available (because the current assumption is you'll be encoding on a large native platform).

**Comment by MarkCallow** [comment]
Yes I am compiling to wasm and only including transcoders for formats supported by WebGL. But even when compiling natively I leave out transcoders like FXT and ATC.

**Comment by richgel999** [comment]
The fix for this will be in the next major release (very early next month, in the optimized build).
