### ISSUE TITLE
Transcoder / Compressor / Encoder CLI

### ISSUE THREAD

**Issue by nickdarnell** [BinomialLLC/basis_universal#141]
I think it's great the transcoder is dependency free.  It would be great if the encoder was as well, if there were an 'compressor' library that didn't know anything about bmp, png...etc.  Instead the commandline encoder utility would be what sucks in half a dozen or more libraries that opens and converts them into some struct the compressor consumes.

**Comment by richgel999** [comment]
I agree - I'm going to convert the encoder to a lib and a separate command line tool. 

As for introducing dependencies, we're not going to be dragging in other 3rd party libraries for image loading/etc. We want to make sure that compiling & porting BasisU is as simple/fast/easy as possible.

**Comment by richgel999** [comment]
The encoder is a lib now. It only depends on the C/C++ runtime.
