### ISSUE TITLE
Progressive loading support

### ISSUE THREAD

**Issue by munsocket** [BinomialLLC/basis_universal#144]
Does basis support progressive loading?
For example can we make a custom loader for three.js?

**Comment by richgel999** [comment]
Not currently,. but it could and I left room for this in the format/transcoders. For ETC1S, once you get the header and global codebooks, you can decode the texture levels as you get them. How important is this use case?

**Comment by munrocket** [comment]
Hmm, pretty important IMHO. Because I am going to create a proposal for future standards in the web.

At the other hand I think we need to simplify documentation also and add flipY feature (if it not exist). Probably this is more important for community.

**Comment by donmccurdy** [comment]
> you can decode the texture levels as you get them. 

@munrocket note that this is possible in the Basis format today, it just has never been implemented in the three.js loaders (or requested, for that matter).

**Comment by munrocket** [comment]
Yeah, we can fetch an image with chunks, drop it into wasm sandbox and waiting for some c++ codec magic.

**Comment by munrocket** [comment]
> you can decode the texture levels as you get them.

Ah I get it. Sorry, language gap.

**Comment by MarkCallow** [comment]
You should take a look at [.ktx2](http://github.khronos.org/KTX-Specification/).

**Comment by richgel999** [comment]
We've exposed container independent transcoding support in the JavaScript wrappers (basis_wrappers.cpp). So you can extract the individual sections of a .basis file and store them in your own file format, then transcode them on the fly as needed.
