### ISSUE TITLE
ETC1S diff bit question

### ISSUE THREAD

**Issue by cwoffenden** [BinomialLLC/basis_universal#147]
The spec says the diff bit is always set:

https://github.com/BinomialLLC/basis_universal/blob/b8c614e758bf16c49292e4c8253d18c82a5d0d24/spec/basis_spec.txt#L14

But the test for a valid ECT1S file in `basisu_etc.h` allows individual mode blocks?

https://github.com/BinomialLLC/basis_universal/blob/b8c614e758bf16c49292e4c8253d18c82a5d0d24/basisu_etc.h#L211

**Comment by richgel999** [comment]
The generic helpers in basisu_etc.h are designed to work with *both* ETC1S and ETC1 texture data, i.e. they aren't specific to Basis Universal files.

Also, the original .basis format supported both ETC1S and ETC1, so you're seeing some of that history in the code. Hope that helps!
