### ISSUE TITLE
16-bit raw heightmaps?

### ISSUE THREAD

**Issue by Leadwerks** [BinomialLLC/basis_universal#148]
Terrain heightmaps seems like a good candidate for supercompression. I was wondering if there were any plans to support this in the future? We typically use 16-bit raw heightmaps (one unsigned short per pixel). I think GIS systems would require greater resolution to handle the range of Earth surface elevation.

**Comment by richgel999** [comment]
We're going to add HDR support at some point, so hopefully this would work in your use case.
