### ISSUE TITLE
Building for Native Android/iOS Support

### ISSUE THREAD

**Issue by NathanaelA** [BinomialLLC/basis_universal#15]
Low priority question, feel free to answer whenever, or point me to resources to help me answer the questions...  :grinning:   

Pretty much all the documentation discusses transcoder support using wasm for the web, which the browser then handles a lot of the heavy lifting with via wasm, the transcoder and webgl. 

However, I have a possible different use case, and I could be completely wrong on this idea.  Can this code be easily be used naively to decode images into the gpu w/o a browser/wasm.   Using XCode & Android NDX to build the code on iOS & Android.    Do I just have to setup a OpenGL 2.x+ session and then point the trancoder to it somehow?    I assume we need the OpenGL session so that it has access to the GPU; correct?

**Comment by atteneder** [comment]
Afaik: yes, you can use the transcoder for that.
Have a look at the `Transcoder detail` section of the readme:
https://github.com/BinomialLLC/basis_universal#transcoder-details

**Comment by NathanaelA** [comment]
@atteneder - Thanks for the answer; I think I totally misunderstood how this works.  :grinning:   

 For some reason I was thinking this actually decoded the textures on the GPU.   

But instead;  I think I finally understand it.  :grinning:  This decodes the texture on CPU into the format you need for you to send the final texture to your GPU, correct?   Which means it (the transcoder) does NOT need access to the GPU...

**Comment by mihaisebea** [comment]
@NathanaelA yes you are correct. It transforms the basis file into a final texture of a type that you specified so YOU can upload that to the gpu using your graphics api.
