### ISSUE TITLE
ERROR: Compressor failed reading a source image!  on JPG

### ISSUE THREAD

**Issue by Samsy** [BinomialLLC/basis_universal#155]
Failed reading a source image on JPG only.

command: 
basisu -mipmap -comp_level 4 -linear -y_flip -output_path ./out/ -no_alpha -file ./in/skybox_day.jpg

Intel Iris Pro 1536 Mo
Mac OS Mojave 10.14.6
cmake version 3.11.2

Built from sources

@richgel999  any idea ?

**Comment by donmccurdy** [comment]
See https://github.com/BinomialLLC/basis_universal/issues/62. Input files must be converted to PNG first.

**Comment by Samsy** [comment]
There is a jpeg decompressor included in the project now.
The build from sources does not work on my machine, but works on others.

**Comment by richgel999** [comment]
I'll investigate. Note that JPEG is a large/complex file format. It's possible your JPEG file uses a feature that the built-in reader doesn't support. PNG should always work.
