### ISSUE TITLE
Transcoder in C

### ISSUE THREAD

**Issue by alex-rass-88** [BinomialLLC/basis_universal#157]
It would be nice if the transcoder was written in C.

**Comment by richgel999** [comment]
Unfortunately, it's a ton of C++ code. It would be a ton of work, with little practical benefit. It's unlikely I can find the time to do this. Also, I would be very hesitant to accept a PR for this sort of change - it would be too large/risky.

FWIW - Once we remove std::vector usage, the code should shrink quite a bit (when compiled to WebAssembly).

**Comment by alex-rass-88** [comment]
I am trying to replace std::vector to tinystl::vector. Transcoder lib size reduse from 4MB to 1.6MB in debug mode. In release with static C++ runtime 700KB.
