### ISSUE TITLE
ASTC and mipmaps fail with THREE.js under WebGL2

### ISSUE THREAD

**Issue by steve-o** [BinomialLLC/basis_universal#158]
WebGL1 works fine, and so does disabling mipmaps in generation of the basis file.

Same results across Chrome, Firefox on MacOS with Intel GPU, and Windows 10 with nVidia RTX Quadro.

demo:  http://ahyoomee.miru.hk/basis/demo/threejs.html

```
.WebGL-0x7f9769868000]GL ERROR :GL_INVALID_OPERATION : glCompressedTexImage2D: width or height invalid for level
253[.WebGL-0x7f9769868000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
threejs.html:1 WebGL: too many errors, no more errors will be reported to the console for this context.
```

**Comment by kenrussell** [comment]
Is this the same issue that was reported in #154 ?

This is being investigated by the WebGL working group in https://github.com/KhronosGroup/WebGL/issues/3117 .

Could you provide all of the source code and assets for your test case and a clear description of how you encoded the Basis files?

CC @shrekshao @lexaknyazev

**Comment by steve-o** [comment]
The textures are 1120x1120, so divisible by 4 at full resolution anyway.  Encoded via:

`basisu -uastc -uastc_level 4 -uastc_rdo_q .75 -mipmap $i`

The demo is basically the THREE.js Basis texture demo (https://threejs.org/examples/?q=basis#webgl_loader_texture_basis) with the context set to WebGL2., i.e.

`const canvas = document.createElement( 'canvas' );
let context = canvas.getContext( 'webgl2', { antialias: true } );
renderer = new THREE.WebGLRenderer( { antialias: true, canvas, context } );`

**Comment by richgel999** [comment]
I'm not very knowledgeable or experienced with some of these technologies, such as THREE.js. If you can provide a source file, or a .basis file, I can at least verify that the file is encoding and transcoding 100% correctly.

**Comment by lexaknyazev** [comment]
@richgel999 
Direct link to the `.basis` file: https://ahyoomee.miru.hk/basis/demo/MIA.basis

**Comment by steve-o** [comment]
Link to the Basis transcoder in THREE.js:

https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/BasisTextureLoader.js

**Comment by steve-o** [comment]
Resized the source image to power-of-two 1024x1024 and it works, thus must be the same issue as #154.

**Comment by lexaknyazev** [comment]
@steve-o 
Could you please confirm on what platforms the original issue emerged?

The title mentions ASTC but that format is not supported on macOS or Windows. Three.js would use BC1 or BC3 transcode targets instead there.

**Comment by steve-o** [comment]
It's the UASTC encoding version of Basis files, as opposed to the ETC1S flavour.  The transcoding target format is BC1 on MacOS (Chrome) and BC7 on Windows (Chrome, Edge, and Firefox).

**Comment by richgel999** [comment]
Looks like the supplied .basis file decodes correctly with the command line tool:

C:\dev\basis_universal-master\bin>basisu MIA.basis
Basis Universal GPU Texture Compressor Reference Encoder v1.12.00
Copyright (C) 2019-2020 Binomial LLC, All rights reserved
Input file "MIA.basis"
File version and CRC checks succeeded
File info:
  Version: 13
  Total header size: 330
  Total selectors: 0
  Selector codebook size: 0
  Total endpoints: 0
  Endpoint codebook size: 0
  Tables size: 0
  Slices size: 1672992
  Texture format: UASTC
  Texture type: 2D
  us per frame: 0 (0.000000 fps)
  Total slices: 11
  Total images: 1
  Y Flipped: 0, Has alpha slices: 1
  userdata0: 0x0 userdata1: 0x0
  Per-image mipmap levels: 11

Image info:
Image 0: MipLevels: 11 OrigDim: 1120x1120, BlockDim: 280x280, FirstSlice: 0, HasAlpha: 1

Slice info:
0: OrigWidthHeight: 1120x1120, BlockDim: 280x280, TotalBlocks: 78400, Compressed size: 1254400, Image: 0, Level: 0, UnpackedCRC16: 0x8550, alpha: 1, iframe: 0
1: OrigWidthHeight: 560x560, BlockDim: 140x140, TotalBlocks: 19600, Compressed size: 313600, Image: 0, Level: 1, UnpackedCRC16: 0x24D9, alpha: 1, iframe: 0
2: OrigWidthHeight: 280x280, BlockDim: 70x70, TotalBlocks: 4900, Compressed size: 78400, Image: 0, Level: 2, UnpackedCRC16: 0xD2C2, alpha: 1, iframe: 0
3: OrigWidthHeight: 140x140, BlockDim: 35x35, TotalBlocks: 1225, Compressed size: 19600, Image: 0, Level: 3, UnpackedCRC16: 0x35E8, alpha: 1, iframe: 0
4: OrigWidthHeight: 70x70, BlockDim: 18x18, TotalBlocks: 324, Compressed size: 5184, Image: 0, Level: 4, UnpackedCRC16: 0xF67E, alpha: 1, iframe: 0
5: OrigWidthHeight: 35x35, BlockDim: 9x9, TotalBlocks: 81, Compressed size: 1296, Image: 0, Level: 5, UnpackedCRC16: 0x90CB, alpha: 1, iframe: 0
6: OrigWidthHeight: 17x17, BlockDim: 5x5, TotalBlocks: 25, Compressed size: 400, Image: 0, Level: 6, UnpackedCRC16: 0xDC1F, alpha: 1, iframe: 0
7: OrigWidthHeight: 8x8, BlockDim: 2x2, TotalBlocks: 4, Compressed size: 64, Image: 0, Level: 7, UnpackedCRC16: 0x611D, alpha: 1, iframe: 0
8: OrigWidthHeight: 4x4, BlockDim: 1x1, TotalBlocks: 1, Compressed size: 16, Image: 0, Level: 8, UnpackedCRC16: 0xF2BB, alpha: 1, iframe: 0
9: OrigWidthHeight: 2x2, BlockDim: 1x1, TotalBlocks: 1, Compressed size: 16, Image: 0, Level: 9, UnpackedCRC16: 0x6E2F, alpha: 1, iframe: 0
10: OrigWidthHeight: 1x1, BlockDim: 1x1, TotalBlocks: 1, Compressed size: 16, Image: 0, Level: 10, UnpackedCRC16: 0xE9D0, alpha: 1, iframe: 0

start_transcoding time: 0.000 ms
Transcode of image 0 level 0 res 1120x1120 format ETC1_RGB succeeded in 2.279 ms
Transcode of image 0 level 1 res 560x560 format ETC1_RGB succeeded in 1.088 ms
Transcode of image 0 level 2 res 280x280 format ETC1_RGB succeeded in 0.374 ms
Transcode of image 0 level 3 res 140x140 format ETC1_RGB succeeded in 0.241 ms
Transcode of image 0 level 4 res 70x70 format ETC1_RGB succeeded in 0.077 ms
Transcode of image 0 level 5 res 35x35 format ETC1_RGB succeeded in 0.026 ms
Transcode of image 0 level 6 res 17x17 format ETC1_RGB succeeded in 0.012 ms
Transcode of image 0 level 7 res 8x8 format ETC1_RGB succeeded in 0.003 ms
Transcode of image 0 level 8 res 4x4 format ETC1_RGB succeeded in 0.002 ms
Transcode of image 0 level 9 res 2x2 format ETC1_RGB succeeded in 0.002 ms
Transcode of image 0 level 10 res 1x1 format ETC1_RGB succeeded in 0.001 ms
....

**Comment by kenrussell** [comment]
@steve-o has this been fixed in recent browser updates? Or has your demo at http://ahyoomee.miru.hk/basis/demo/threejs.html been changed to use power-of-two textures?

**Comment by steve-o** [comment]
@kenrussell from visual inspection of output it looks like Chrome Canary and Safari both work, whilst Firefox Developer has not made progress.

**Comment by kenrussell** [comment]
Thanks for testing. I've filed the following browser bugs:

Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1675410
WebKit: https://bugs.webkit.org/show_bug.cgi?id=218595

I suggest this bug be closed in favor of https://github.com/KhronosGroup/WebGL/issues/3117 .
