### ISSUE TITLE
An Android library of Basis Universal

### ISSUE THREAD

**Issue by rawnsley** [BinomialLLC/basis_universal#159]
Is there an easy way of using Basis Universal in a native Android app? Ideally for use in a JVM app via JNI.

**Comment by richgel999** [comment]
Hi - Can you compile the C++ transcoder (contained in the "transcoder" directory) to a library, then create a JNI wrapper for it? It's just a single .cpp file, so it should be easy to compile. You could study the C++ wrappers for WebAssembly as a starting point.

**Comment by richgel999** [comment]
I'm going to close this comment, as it doesn't seem to be pointing out a bug or issue, but just a question. Please let me know if there's anything I can do. (I don't have much experience on Android, other than writing a "Hello World!" type app a few years ago.)
