### ISSUE TITLE
Is Basis supported on all devices?

### ISSUE THREAD

**Issue by Ben-Mack** [BinomialLLC/basis_universal#16]
Can we ensure that Basis is supported on all devices (like jpeg, png)?

Or should I prepare fallback to jpeg, png in case some devices does not support any compressed texture formats (Is there any device like that?)

**Comment by shrekshao** [comment]
AFAIK, you can fall back to RGB from DXT using some library like the texture demo is doing here: https://github.com/BinomialLLC/basis_universal/blob/master/webgl/texture/index.html#L211

**Comment by richgel999** [comment]
Yes, absolute worse case, you can fall back to RGB 565 or 24/32-bit RGB. But AFAIK, Basisu's transcoder should be able to output at least one GPU format that virtually every GPU supports. 
Between ETC1/2, BC1-5, BC7, and PVRTC1, that's a lot of GPU's. And ASTC is coming. 
To get ATITC (an older obscure format supports on Qualcomm Adreno), you can use this library to convert the basisu BC1 data to ATITC on the fly:
https://github.com/Triang3l/S3TConv
We could easily add ATITC if there was interest - it seems pretty niche. It's the only format I can think of that we don't support out of the box.

**Comment by richgel999** [comment]
I would examine the devices you will be supporting *and* the API's, and determine if you actually need a fallback. This is what game developers typically do. The Unity engine will fall back to uncompressed if it needs to.
I'm considering adding 565 and 8888 fallback transcoders, to make this easier. Right now, you can convert the ETC1 data to RGB(A).

**Comment by richgel999** [comment]
I've closed this as I think I've answered the question. There still remains the question of whether or not we should implement a fallback path in the transcoder itself, to make it easier for users to do that.

**Comment by Ben-Mack** [comment]
Thank you for your detailed answer!

I'm working with WebGL, so there's no specific target device, I always aim for as much compatibility as possible.

+1 for implement fallback directly in the transcoder, as it seems like a universal method.
