### ISSUE TITLE
UASTC modes 0/5/18 to BC7 mode 6 opaqueness preservation

### ISSUE THREAD

**Issue by lexaknyazev** [BinomialLLC/basis_universal#161]
According to the spec and the source code, UASTC modes 0/5/18 (RGB) are transcoded to BC7 mode 6 (RGBA).
The latter has 7 bits per channel plus 1 p-bit per endpoint. 

Does it mean that for some input combinations the transcoded alpha value would be 254/255 because unset p-bit may give smaller overall error? Are such configurations prevented during encoding?

**Comment by richgel999** [comment]
Yes, some output values will be 254. This also occurs with our (and some other) BC7 encoders. So far, it's not been an issue.
