### ISSUE TITLE
UASTC to ETC1 luma estimation

### ISSUE THREAD

**Issue by lexaknyazev** [BinomialLLC/basis_universal#164]
The UASTC spec says this about choosing ETC1 selectors:
> This step can be accelerated by computing the errors in a luma space with RGB component weights of (1,1,1).

Following the discussion in #162, we may need to revise this as well. Specifically:
- The texture may contain color or non-color data. In the former case, luma is usually defined as a sum weighted with (0.2126, 0.7152, 0.0722). Getting the "correct" luma may also require decoding non-linear transfer function.
- Despite the spec language, the source code uses weighted sum with sRGB-like factors rounded to integers:
https://github.com/BinomialLLC/basis_universal/blob/102275a96475933079c4d415f0eb201ce530308e/transcoder/basisu_transcoder.cpp#L13224

**Comment by richgel999** [comment]
Got it - I'll document this more. I'm hesitant to support other scale factors other than linear, based purely off my experience with my other ETC1S encoders. 

ETC1S is so bad at handling chroma variation within 4x4 texel blocks that it doesn't help much to support different scale factors here. 

My reasoning with the current code: I wanted one set of scale factors that would work well enough for a wide variety of textures. ETC1S already struggles with normal maps, so switching to linear won't help much. In practice, even with my other shipping RDO ETC1/ETC1S encoders, the users always enable perceptual colorspace metrics (not linear), even on normal maps, which results in higher quality.

**Comment by richgel999** [comment]
For UASTC->ETC1 transcoding, I'm hesitant to document *exactly* how this is done in the UASTC specification. The encoder only looks at transcoded BC7 and ASTC error, not ETC1 error, so the user can transcode to ETC1 any way they want. The best way will depend on the capabilities of the device doing the transcoding: SIMD or not, CPU or GPU, etc. The transcoder could also choose to completely ignore the ETC1/ETC2 EAC A8 hints, if it really wanted higher quality. I think the spec should only document how the hints themselves are interpreted, and leave the actual transcoding to ETC1, ETC2 EAC A8, PVRTC1, etc. up to the developer.

**Comment by richgel999** [comment]
I've changed the wording on the UASTC spec in our wiki to "The last step is computing the texel indices. This step can be accelerated by computing the errors in a luma space with RGB component weights of (1,1,1), although other methods are possible too."

I think the spec should require bitwise accurate BC7 and ASTC transcoding, and for the other texture formats some variation is fine.

**Comment by richgel999** [comment]
I've changed the wording on the UASTC spec in our wiki to "The last step is computing the texel indices. This step can be accelerated by computing the errors in a luma space with RGB component weights of (1,1,1), although other methods are possible too."

I think the spec should require bitwise accurate BC7 and ASTC transcoding, and for the other texture formats some variation is fine.
