### ISSUE TITLE
REUSE license-checking

### ISSUE THREAD

**Issue by oddhack** [BinomialLLC/basis_universal#165]
Would you be open to a PR which configures the repository for REUSE (https://reuse.software/) compliance? REUSE is a standardized method for declaring copyright and licensing, which we're adopting inside Khronos. This repository is incorporated in the https://github.com/KhronosGroup/KTX-Software/ project, which I've been asked to make REUSE-compliant. Since I'll need to capture this knowledge for KTX-Software in any event, it is straightforward to do it here as well. The PR would add full text of the relevant licenses under the LICENSES/ directory, document special cases in .reuse/dep5, and encourage people to run "reuse lint" when changing the repo (could also be done in CI).

Related: the repo README refers to tcuAstcUtil.cpp as a 3rd party code dependency under an AOSP copyright. It appears to me that the actual files in question are basisu_astc_decomp.{cpp,h} - were these renamed from the AOSP originals?

**Comment by richgel999** [comment]
Let me research this and get back to you. There are some contractual terms that I need to make sure the REUSE compliance doesn't break.

**Comment by oddhack** [comment]
Thanks. BTW here's what we put in the KTX-Software repository for files which didn't already have licenses REUSE could parse:

```
Files: lib/basisu/*
Copyright: 2019-2020 Binomial LLC
License: Apache-2.0

Files: lib/basisu/apg_bmp.* lib/basisu/CMakeLists.txt lib/basisu/webgl/transcode
r/CMakeLists.txt
Copyright: 2019 Anton Gerdelan
License: Apache-2.0

Files: lib/basisu/basisu_astc_decomp.*
Copyright: 2016 The Android Open Source Project
License: Apache-2.0

Files: lib/basisu/lodepng.*
Copyright: 2005-2019 Lode Vandevenne
License: Zlib
```

**Comment by richgel999** [comment]
If you submit a PR I'll merge it over. Thanks!
