### ISSUE TITLE
Provide a basisu WASM build with example for texture conversion in browser client.

### ISSUE THREAD

**Issue by EricEisaman** [BinomialLLC/basis_universal#167]
The CLI for basisu is a common use case but so is conversion in the browser client, particularly when users are loading texture assets.  I see considerable value in providing a WASM build with an accompanying example.

**Comment by richgel999** [comment]
Have you seen the two examples in the "WebGL directory:
https://github.com/BinomialLLC/basis_universal/tree/master/webgl

(We had a couple Web engineers compose these samples.) There's also a sample in the webgl_videotest directory, but it's older.

**Comment by EricEisaman** [comment]
Thanks @richgel999.  Is the process identical for the new release?

**Comment by gtk2k** [comment]
I also want a WebAssembly build of basisu.

**Comment by richgel999** [comment]
We have exposed the entire encoder codec to Javascript using WebAssembly - we're testing/validating this now and it should be out within a few days or so.

**Comment by richgel999** [comment]
It's out now. Thanks!

**Comment by EricEisaman** [comment]
Wow!  Thank you @richgel999 !
