### ISSUE TITLE
how to convert .basis to png with api or function

### ISSUE THREAD

**Issue by lihongyi1234** [BinomialLLC/basis_universal#168]
i compress a .png to .basis success ,and get buffer through function get_output_basis_file,then i want to transcoder .basis to png ,unfortunately it failed, start_transcoding()  validate_header_quick() failed, i want to know if there is sonething wrong with my prohram or something omitted.

        auto buffer = comp.get_output_basis_file();
	basist::basisu_transcoder_init();
	basist::etc1_global_selector_codebook sel_codebook(basist::g_global_selector_cb_size,basist::g_global_selector_cb);
	basist::basisu_transcoder trans(&sel_codebook);
	trans.start_transcoding(&buffer,buffer.size());
	auto nums = trans.get_total_images(&buffer, buffer.size());

**Comment by richgel999** [comment]
At first glance, this code sequence looks correct. Can you single step into start_transcoding() and see where exactly it's failing?

Can you dump the output .basis file data to a disk file, then validate the file using the command line tool? This will call unpack_and_validate_mode(), which will load the file and then transcode it.

**Comment by richgel999** [comment]
If you save the file to dis, and it validates OK, then you are doing something wrong in there with the transcoder. I would study and single step through unpack_and_validate_mode() on your file, or the WebAssembly wrappers, to figure out what's happening.

**Comment by lihongyi1234** [comment]
I solve the problem success,the program is follow:

basist::basisu_transcoder_init();
basist::etc1_global_selector_codebook sel_codebook(basist::g_global_selector_cb_size, basist::g_global_selector_cb);
basist::basisu_transcoder dec(&sel_codebook);
if (!dec.validate_file_checksums(&basis_data[0], (uint32_t)basis_data.size(), true))
if (!dec.start_transcoding(&basis_data[0], (uint32_t)basis_data.size()))

**Comment by lihongyi1234** [comment]
@richgel999  I went some problem when upload .ktx ( transcode from .basis file) to unity texture2d ,I want to get texture from .ktx file, but the output texture is not the same as initial one.  the main program(C#) is follow:

buffer = File.ReadAllBytes(file_path);
Texture2D texture= new Texture2D(1024, 1024, TextureFormat.ETC_RGB4, false);
texture.LoadRawTextureData(buffer);

the result is follow:

![image](https://user-images.githubusercontent.com/36233282/92233376-c9918c00-eee2-11ea-8ef6-247ea3e6da58.png)

i want to if where is header info when you write to .ktx file or something else should be attended
