### ISSUE TITLE
Add build instruction for Windows

### ISSUE THREAD

**Issue by ThreeDfish** [BinomialLLC/basis_universal#170]
Please add some build instructions for building this under Windows 10.

I already have Visual Studio build tools installed...

I installed CMake and it successfully created the build files, and then I installed make using Chocolaty

```ps
choco install make
```

and then I ran make and it said: "make: *** No targets specified and no makefile found. Stop."

So, I'm guessing that the build instructions are different if trying to build under windows.

**Comment by richgel999** [comment]
If you type "cmake ." under Windows in the root of the project directory,  you'll get a solution file named "basisu.sln". You can then use this solution to build with Visual Studio 2019. Hope that helps.

C:\dev\bus\basis_universal>cmake .
-- Building for: Visual Studio 16 2019
-- The C compiler identification is MSVC 19.24.28319.0
-- The CXX compiler identification is MSVC 19.24.28319.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Initial BUILD_X64=ON
Initial CMAKE_BUILD_TYPE=
basisu build type: Release
Building 64-bit
-- Configuring done
-- Generating done
-- Build files have been written to: C:/dev/bus/basis_universal
