### ISSUE TITLE
Source code license clarification: language port

### ISSUE THREAD

**Issue by KillaMaaki** [BinomialLLC/basis_universal#179]
Hello, I'm currently looking at potentially porting the transcoder portion of the basis universal source to another language (Zig). I'd love to get some clarification on the Apache 2 license, as I'm not entirely sure how it applies in this case. Should a source port be made to have the same license, or does it just need to retain a copy of the original license, or...?

**Comment by richgel999** [comment]
If it's a port, it should retain a copy of the original Apache 2.0 license somewhere. Any new code can be covered by your copyright/license in the port.
