### ISSUE TITLE
Encoding single-channel image data

### ISSUE THREAD

**Issue by rawnsley** [BinomialLLC/basis_universal#182]
I would like to encode a grayscale image into basisu format and then decode it to a platform-appropriate format such as ETC2_R11 or the desktop-friendly equivalent, but I have a couple of questions:

1. What would the command line look like for the encoding? i.e. do I have to specify that I want to use single channel EAC?
2. How do I know at runtime that the .basisu file holds single channel data?

For context: I'm encoding lightmaps and the 8bpp RGB ETC 4x4 coding is very noisy so I'm hoping that an EAC encoding of luminance-only data will double the effective bpp value and reduce the noise.

**Comment by richgel999** [comment]
There are currently two formats internally - ETC1S and UASTC, with very different pros & cons. UASTC supports single channel data internally, but it's 8bpp (with RDO encoding+LZ you can get it down to around 4-6bpp or so). I suggest you play around encoding to each format:

basisu file.png
or 
basisu -uastc file.png

To unpack to all supported GPU formats, do "basisu file.basis" and you can see what it looks like. 

The codec will treat single channel data as a grayscale image. Internally, there are optimizations for single channel textures for both ETC1S/UASTC. Hope this helps.

**Comment by rawnsley** [comment]
Thanks for the info @richgel999. I'm struggling to demonstrate the advantage of the single channel compression. If I take two identical grayscale images where one is saved in PNG RGB format and the other in PNG grayscale format I would expect the PSNR for the grayscale to be better than the RGB, but they are both 58.290 dB

I'm using the command line `basisu -uastc -debug -stats testcard-gray.png`

I did wonder if the large flat areas were skewing the result, but I get the same result for [less trivial images](https://homepages.cae.wisc.edu/~ece533/images/baboon.png) as well.

**Grayscale (8bpp)**
![testcard-gray](https://user-images.githubusercontent.com/303516/102230727-22f75700-3ee5-11eb-9942-390506d5d457.png)

**RGB (24bpp)**
![testcard-rgb](https://user-images.githubusercontent.com/303516/102230737-2559b100-3ee5-11eb-94ef-3f24cb59349a.png)

**Comment by richgel999** [comment]
In ETC1S mode, we have some optimizations for storing grayscale endpoint palettes (see basisu_backend::encode_endpoint_palette()). Also, UASTC mode has some dedicated single channel or single channel+alpha modes. But it's still, at its heart, a RGB or RGBA system. 

>How do I know at runtime that the .basisu file holds single channel data?

We don't have a flag in the header yet that indicates this, but it's a good idea!
