### ISSUE TITLE
Very slow compression compared to older version

### ISSUE THREAD

**Issue by DolphinIQ** [BinomialLLC/basis_universal#183]
Hi
Using the same textures, Im getting very different compression speeds on different basisu versions:

**Basisu v1.12.00 (exe size: 3663kB):**
512x512 png: **27.506s**
2048x2048 png: **396.708s**

It took so long I thought it was broken, or there is something wrong with my computer, but trying an older version I got acceptable results:

**Basisu - v1.08.00 (exe size: 1138kB):**
512x512 png: **0.920s**
2048x2048 png: **18.021s**

Using command:
`basisu x.png`
Also tried `-no_auto_global_sel_pal` flag according to [this thread](https://github.com/BinomialLLC/basis_universal/issues/75), but it had no noticeable effect on the compression speed.

My computer specs:
Windows 7
64 bit OS
8,00 GB RAM
Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz

**Comment by xiaobooo** [comment]
I also think it's too slow.

**Comment by richgel999** [comment]
This is very strange - I'll investigate.

**Comment by richgel999** [comment]
These are massive slowdowns, which I'm not seeing. Are you sure you build the executable in Release?

**Comment by DolphinIQ** [comment]
Sorry, I know very little about builds and was using the debug executable. Same images with the release exe:
512x512 - 1.3s
2048x2048 - 19.8s

**Comment by richgel999** [comment]
No problem - thanks for the report and the timings!
