### ISSUE TITLE
Win version cannot run

### ISSUE THREAD

**Issue by Sea-DH1** [BinomialLLC/basis_universal#184]
Win version cannot run

I run basse.exe and it disappears

**Comment by playmer** [comment]
This sounds like you might be opening it in explorer or VS which would make the command prompt open and then immediately close. but the encoder is a command line program. You have to give it command line arguments. There's an example on the read me on the read me: basisu -uastc -uastc_level 2 -uastc_rdo_q .75 x.png

But perhaps I misunderstood?

**Comment by Sea-DH1** [comment]
> This sounds like you might be opening it in explorer or VS which would make the command prompt open and then immediately close. but the encoder is a command line program. You have to give it command line arguments. There's an example on the read me on the read me: basisu -uastc -uastc_level 2 -uastc_rdo_q .75 x.png
> 
> But perhaps I misunderstood?

No, I ran it directly

**Comment by playmer** [comment]
From the cmd? Can you explain exactly what you did?

**Comment by richgel999** [comment]
There is no "basse.exe". If you build it correctly, you'll get an EXE named "basisu.exe" or "basisud.exe" in the bin directory. Open cmd.exe, change to the "bin" directory, then run basisu.exe. What happens?

**Comment by richgel999** [comment]
I've built the Windows version from the tip, and it runs OK. I develop under Windows. So I'm closing this. Thanks!
