### ISSUE TITLE
How to make it run faster?

### ISSUE THREAD

**Issue by xiaobooo** [BinomialLLC/basis_universal#186]
I think it's too slow.

 ubuntu 、a single core CPU

Basis Universal GPU Texture Compressor Reference Encoder v1.12.00
Copyright (C) 2019-2020 Binomial LLC, All rights reserved
Processing 1 total file(s)
Read source image "11_l.jpg", 2048x2048
Total basis file slices: 1
Slice: 0, alpha: 0, orig width/height: 2048x2048, width/height: 2048x2048, first_block: 0, image_index: 0, mip_level: 0, iframe: 0
Wrote output .basis file "11_l.basis"
Compression succeeded to file "11_l.basis" in 17.762 secs

If i want to deal with a lot of pictures. How can i make it faster.

**Comment by richgel999** [comment]
I'm working on a faster encoder. For now, find a machine with more cores.

**Comment by xiaobooo** [comment]
one core: 24secs
two cores: 17secs
four cores: 10secs
eight cores: 7secs
 Double cores can't make 24 secs to 12 secs. It's a waste of resources.

**Comment by richgel999** [comment]
This library is provided 100% for free. By all means, you may feel free to sponsor the hard work to make a faster encoder. Or, you are free to use an alternative library. Thank you.
