### ISSUE TITLE
Why not compress the UASTC stream?

### ISSUE THREAD

**Issue by rawnsley** [BinomialLLC/basis_universal#190]
Compressing the ETC1S streams is a great feature that reduces the size of the basis files so I don't understand why it wasn't applied to UASTC streams as well.

You even go to the trouble of allowing us to reduce the entropy in the stream to improve compression.

Obviously we can choose to compress the stream ourselves, but only in specific applications. Not, for instance, in GLTF files, which appear to be the canonical use case for basisu.

Am I missing something? Is this a feature of the ktx2 container that I have overlooked that fills the gap?

**Comment by lexaknyazev** [comment]
KTX v2 container (and therefore glTF's way of embedding BasisU) supports Zstandard compression for UASTC payloads.

**Comment by rawnsley** [comment]
@lexaknyazev Great - thanks for clarifying that. It might be worth putting it in the documentation somewhere because at the moment it is framed very much as if you must choose between small low-quality ETCS1 and large high-quality UASTC.

**Comment by lexaknyazev** [comment]
What documentation are you referring to?

Relevant glTF extension section:
https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_texture_basisu#ktx-v2-images-with-basis-universal-supercompression

KTX v2 section:
https://github.khronos.org/KTX-Specification/#_supercompressionscheme

**Comment by rawnsley** [comment]
The [readme ](https://github.com/BinomialLLC/basis_universal/blob/master/README.md) from this repository:

> The ETC1S system includes built-in data compression, while the UASTC system includes an optional Rate Distortion Optimization (RDO) post-process stage that conditions the encoded UASTC texture data in the .basis file so it can **be more effectively LZ compressed by the end user**.
