### ISSUE TITLE
Is cTFBC7_ALT deprecated?

### ISSUE THREAD

**Issue by fintelia** [BinomialLLC/basis_universal#193]
Per the comments in basisu_transcoder.h it seems that the special BC7 modes are no longer supported and just alias to the normal BC7 mode.

https://github.com/BinomialLLC/basis_universal/blob/2952f6dc67cf50f75004619a9a6637a2b87ff81f/transcoder/basisu_transcoder.h#L91-L96

However, `cTFBC7_ALT` seems to retain a distinct value. I don't see anywhere in the code where `cTFBC7_RGBA` and `cTFBC7_ALT` are treated differently, so is this an oversight or an indication that the ALT version will be handled specially in the future?

**Comment by richgel999** [comment]
Yes - we reorganized the enums (and added some new ones), but I left the older ones there for backwards compatibility. I wouldn't use them, but they'll never go away.

**Comment by fintelia** [comment]
Is there a reason that all the other old enums are set equal to cTFBC7_RGBA (=6) but cTFBC7_ALT is set to 7?
