### ISSUE TITLE
CI on master is currently failing

### ISSUE THREAD

**Issue by UebelAndre** [BinomialLLC/basis_universal#194]
Not sure how to ping that since the change (https://github.com/BinomialLLC/basis_universal/commit/62539278e10d106f52b9a05134ef3e8267b22a02) that introduced the failure wasn't associated with a PR. Haven't investigated the failure, just wanted to raise awareness somehow.

**Comment by UebelAndre** [comment]
@richgel999 Would you be able to take a look? 🙏

**Comment by richgel999** [comment]
yup - looking at it

**Comment by richgel999** [comment]
all fixed - thanks!
