### ISSUE TITLE
BC1 and Firefox

### ISSUE THREAD

**Issue by titansoftime** [BinomialLLC/basis_universal#2]
The readme (https://github.com/BinomialLLC/basis_universal/tree/master/webgl) states that Firefox does not support BC1 format. It does and has for some time now with the extension "WEBGL_compressed_texture_s3tc" as opposed to "WEBKIT_WEBGL_compressed_texture_s3tc" which the demo tests. 

https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_compressed_texture_s3tc

**Comment by richgel999** [comment]
Thanks, I'll be fixing this.

**Comment by richgel999** [comment]
I have checked in a fix for this.
Thanks!
Rich

**Comment by richgel999** [comment]
The "texture" demo works on Firefox, and I updated the readme
