### ISSUE TITLE
Potential dereference of null pointer

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [BinomialLLC/basis_universal#20]
line 4934: calling function ucvector_init() to initialize 'data'
https://github.com/BinomialLLC/basis_universal/blob/21ab9bebb5b067ccee273d5ce82ad3eb65656ac8/lodepng.cpp#L4934

in function ucvector_init()
line 245, 'data' may be assigned as null pointer.
https://github.com/BinomialLLC/basis_universal/blob/21ab9bebb5b067ccee273d5ce82ad3eb65656ac8/lodepng.cpp#L245

line 4936: 'data' is used as argument while calling function ucvector_push_back()
https://github.com/BinomialLLC/basis_universal/blob/21ab9bebb5b067ccee273d5ce82ad3eb65656ac8/lodepng.cpp#L4936

while calling function ucvector_push_back()
line 263:  dereference 'p->data' without checking whether it is a null pointer.
https://github.com/BinomialLLC/basis_universal/blob/21ab9bebb5b067ccee273d5ce82ad3eb65656ac8/lodepng.cpp#L263

(Our tool also found that in line 220 there is a check for 'data' which is the return value of calling function 'lodepng_realloc()', and assume that the value (data) is null. Even if this case will hardly happen, it is better to add an 'assert(p->data)'  as a better software engineering perspective)

**Comment by richgel999** [comment]
Ok, this is in lodepng: 
https://lodev.org/lodepng/
We only use this for PNG reading on the encoder. So this can't affect the transcoder at all, which is good.
I will look at this and see if I can fix it.

**Comment by richgel999** [comment]
Also note that we have not seen any null ptr derefs inside of lodepng, yet.

**Comment by richgel999** [comment]
I've added a check for null to uivector_push_back(). It will appear in the UASTC update in a few hours today.
