### ISSUE TITLE
"ambiguous call to overloaded function" in basisu_comp.cpp

### ISSUE THREAD

**Issue by MarkCallow** [BinomialLLC/basis_universal#208]
In 3 places, lines 133, 577 & 1271 with VS 2015 & 2017.

This is related to the change to put miniz it its own namespace, I think. Here is one of the errors:

```
C:\projects\ktx\lib\basisu\encoder\basisu_comp.cpp(133): error C2668: '_wassert': ambiguous call to overloaded function [C:\projects\ktx\build-win-Debug\ktx.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\assert.h(26): note: could be 'void _wassert(const wchar_t *,const wchar_t *,unsigned int)'
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\assert.h(26): note: or       'void buminiz::_wassert(const wchar_t *,const wchar_t *,unsigned int)'
  C:\projects\ktx\lib\basisu\encoder\basisu_comp.cpp(133): note: while trying to match the argument list '(const wchar_t [2], const wchar_t [51], unsigned int)'
```

You probably just need to change the`assert` to `::assert` or `buminix::assert` whichever is more appropriate. I can't check right now as I'm waiting for my PC to finish installing a Windows update.

I'm surprise you didn't see this error.

**Comment by richgel999** [comment]
I build with VS 2019, clang and gcc under Ubuntu v18, and don't see this. I'll try an earlier version of VS. (Note I don't officially support anything earlier than 2019 as even MSVC 2019 is very buggy, but if it's a trivial fix I'll do it.)

**Comment by richgel999** [comment]
Fixed

**Comment by MarkCallow** [comment]
Thanks for the quick fix. Like you my clang and gcc builds were successful. I haven't been using  VS 2019 because around v16.5 a bug was introduced that caused the compiler to bail out with an internal error when compiling my project. I've just updated to v16.9.1 and thankfully the bug is fixed.
