### ISSUE TITLE
error C2990: 'std::iterator': non-class template has already been declared as a class template

### ISSUE THREAD

**Issue by MarkCallow** [BinomialLLC/basis_universal#211]
In one of my tools I

```
#include "encoder/basisu_resampler.h"
#include "encoder/basisu_resampler_filters.h"
```

so I can use your resampler. But in v1.13 when I try to compile this tool I get the following error:

```
c:\projects\ktx\lib\basisu\transcoder\basisu_containers.h(1019): error C2990: 'std::iterator': non-class template has already been declared as a class template [C:\projects\ktx\build-win-Debug\tools\toktx\toktx.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xutility(564): note: see declaration of 'std::iterator'
  c:\projects\ktx\lib\basisu\transcoder\basisu_containers.h(1855): note: see reference to class template instantiation 'basisu::hash_map<Key,Value,Hasher,Equals>' being compiled
```

I'm using VS 2019. The same happens with VS 205 and VS 2017. It compiles fine with clang and gcc.

In `basisu_containers.h` at line 1019 there is the statement

```
friend class iterator;

```

but this is before basisu::iterator is defined (line 1208). If I put the statement

```
class iterator;
```

at line 1014, before the `friend statement, then everything compiles.

What I can't figure out is how your stuff that includes these files, or rather `basisu_containers.h` compiles. Maybe it is because I have a `using namespace std;` statement though it does come after the resampler headers are included. If I add `class basisu::iterator` before I include `basisu_resampler.h` I get an error that there is no iterator class in basisu so that doesn't work.

I suspect a declaration of the class like I added to basisu_containers.h is more correct c++ since the definition comes after first use but I'd prefer to get my code working without having to modify yours. Any clues?

**Comment by MarkCallow** [comment]
I got a flash of inspiration. I can fix the issue in my code by adding

```
namespace basisu {
    class iterator;
};
```

before I include `encoder/basisu_resampler.h`. I still think you should forward declare the iterator class.

**Comment by richgel999** [comment]
I'm going to check this in - it doesn't break basisu, and I was unable to repro your problem, but perhaps it'll fix it:

   class hash_map
   {
   public:
      // new lines
      class iterator;
      class const_iterator;
   private:

**Comment by richgel999** [comment]
This is in - reopen if it doesn't help.

**Comment by MarkCallow** [comment]
Thanks Rich. That fixed the problem. The error occurred only in a file with a `using namespace std;` line even though it was after the includes. I suspect it is hitting an edge case bug in MSVS where, because the iterator in `friend class iterator` was not previously declared, the compiler took it to be std::iterator.

**Comment by MarkCallow** [comment]
By the way, I don't think you need the `public:` here. In my tests before filing the issue I found adding the line `class iterator` fixed the problem.
