### ISSUE TITLE
dracoloader+basis

### ISSUE THREAD

**Issue by lidonghai1** [BinomialLLC/basis_universal#22]
Using Draco Loader is normal for Android. It can't be displayed in apple, it can't be parsed correctly

**Comment by donmccurdy** [comment]
@lidonghai1 This repository is not related to Draco, or to loading Draco files. What 3D library are you using, if any? That's probably the place to report this problem. You'll also need to include a demo or code to help others reproduce the problem, regardless of where you're reporting the issue.
