### ISSUE TITLE
wegl program, the textsure quality is too bad when it is drawed in the canvas. 

### ISSUE THREAD

**Issue by raizo-coder** [BinomialLLC/basis_universal#221]
![image](https://user-images.githubusercontent.com/54347262/114269954-49b13e80-9a3c-11eb-9591-9700b7753ef4.png)

sorry. my english is not good.
I already setted premultipliedAlpha value, but the result is not good, how can i do?  I need some help, please

0. covert png to basis file. 
cmd:
[ ./basisu.exe -uastc -uastc_level 4 -linear -file pet_10002_7_2.png -output_file pet_10002_7_2.basis]

1.  var gl = elem('canvas').getContext('webgl', {
      premultipliedAlpha: true
});
2. gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL, true)
    gl.compressedTexImage2D(0x0DE1,0,this._format,this._w,this._h,0,this._image);
   gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL, false)

**Comment by raizo-coder** [comment]
![pet_10002_0_0](https://user-images.githubusercontent.com/54347262/114270523-73b83000-9a3f-11eb-991b-2b5d2550ae94.png)
here is the png file, if some one need.

**Comment by richgel999** [comment]
Hi,
Also, is there a reason why you're using the "-linear" option? Your texture looks sRGB to me. Using -linear will slightly lower quality.
"-uastc -uastc_level 4 -linear"

I compressed your .PNG to UASTC .KTX2 using the -stats option, and it gets over 40 dB for both RGB and Alpha. So it's not the compressor, i.e. the UASTC texture is good.

![image](https://user-images.githubusercontent.com/6934809/114458140-ce22cf00-9bac-11eb-8db6-ee7cfe3fd2ea.png)
![image](https://user-images.githubusercontent.com/6934809/114458147-d0852900-9bac-11eb-94ab-870a34116451.png)

**Comment by richgel999** [comment]
If you use the command line tool on your .basis or .KTX2 file, it'll transcode and unpack it to PNG and various GPU texture formats. You can then see exactly what texture or image data you'll get when you transcode the .basis or .KTX2 file.

**Comment by richgel999** [comment]
This very much looks to be a content and/or problem with how you're using WebGL - so I'm closing this. Feel free to reopen if you find an issue with Basis Universal itself.

**Comment by raizo-coder** [comment]
OK thank U
