### ISSUE TITLE
Decoded image data CRC check failed.

### ISSUE THREAD

**Issue by NILNULLNONE** [BinomialLLC/basis_universal#223]
I get the error message "Decoded image data CRC check failed on slice 0!" when I try to compress this image(Below, a 16 * 16 nearly black image).

![e6f954de-4e1ba30d-4dfabf9f-e63fab13-RGBToBasisIn](https://user-images.githubusercontent.com/35492514/114493788-be0efc00-9c4d-11eb-9a4e-d1443e3fd755.png)

**Comment by richgel999** [comment]
Thanks - I'm looking at this. Ouch.

**Comment by richgel999** [comment]
This is a legit bug. We missed it (our test suite has an all-black 4x4 texture, but not 16x16). Working on fix.

**Comment by richgel999** [comment]
Got a fix. Testing it now. I'll have it checked in today (probably within an hour). Thanks a bunch for reporting it!

**Comment by richgel999** [comment]
The fix is checked in. Thanks again!
