### ISSUE TITLE
Support for image resize

### ISSUE THREAD

**Issue by zeux** [BinomialLLC/basis_universal#224]
One feature that is present in `toktx` and absent in `basisu` is resizing the image to a given size before mipmap generation / compression. `basisu` provides a variant of this, `resample_factor`, but it's insufficient - in addition to a resample factor option you might need to:

1. Round width/height to a multiple of 4; this is because textures with base level that has dimensions that aren't divisible by 4 can't be loaded by DX11/DX12 due to runtime restrictions, and similarly WebGL restricts the dimensions when using WEBGL_compressed_texture_s3tc
2. Round width/height to the next power of 2; this is because WebGL1 only supports power of two textures when using DXT compression via WEBGL_compressed_texture_s3tc (which mandates that every mip level has dimensions that are 1, 2 or a multiple of 4, which translates to a power-of-two requirement for the base level).

To be able to use basisu to target these we either need two options such as -resample_4 and -resample_pot, or a custom `-resample X Y` that resizes the image to the target dimensions and expect the caller to do the math themselves (`gltfpack` does that when using `toktx`).

I'd be happy to contribute an implementation of either option; I would probably default to `-resample X Y` because that allows more flexibility on the caller side (e.g. in addition to the above you may also want to limit the base image size to a given maximum or round to nearest power of two instead of nearest or ...), at the expense of having to parse image headers to know the source image size.

**Comment by richgel999** [comment]
Yes, all good points. I've been merging submitted PR's as fast as I can given our milestone obligations. As this would be a very targeted change (only impacting image resizing, which by default isn't enabled), if you submit a PR that just does that I can quickly accept it. We just merged over user submitted mipmaps, but this needs to be exposed in the command line tool and JS builds.

The most difficult (slowest) PR's to accept are ones that impact large amounts of code, or ones that impact the core ETC1S/UASTC compressors in some way. They are difficult to test/validate. Image resizing should be very simple.
