### ISSUE TITLE
Transcode format selection

### ISSUE THREAD

**Issue by dpwiz** [BinomialLLC/basis_universal#227]
I use `basisu` tool to generate `ktx` files with BC-compressed data (because the other tools either won't work at all or provide low-quality results).

Current `-unpack` action dumps quite a few files (500+mb from one run - easy!) and I only want the `ktx` file with a single transcoded format.

I made a small [patch] that I rebase once in a while, but this is suboptimal for many reasons.

Before:

    $ basisu -unpack brickwall_normal.basis
    ... encoder output ...
    ... tons of transcoded KTXs and PNGs that I have to delete ...
    Wrote KTX file "brickwall_normal_transcoded_BC7_RGBA_0000.ktx"
    ... more of transcoded KTXs and PNGs that I have to delete ...

After:

    $ basisu -unpack -only 6 brickwall_normal.basis
    ... encoder output ...
    Wrote KTX file "brickwall_normal_transcoded_BC7_RGBA_0000.ktx"
    ... tons of transcoded PNGs that I have to delete ...

[patch]: https://gitlab.com/dpwiz/basis_universal/-/commit/6a5357c1944aac8195d69de4fa02822c2731f47b?w=1

**Comment by richgel999** [comment]
Got it - I can easily add this. It's a great idea. It's coming.

There are two options that are similar already. -no_ktx and -etc1_only. It sounds like you want an option that only writes KTX files for a specific format. No problem.

**Comment by dpwiz** [comment]
Is this still a great idea? :smile:

**Comment by richgel999** [comment]
Yes, I'll add a -ktx_only flag in the Jan. release. Standby!

**Comment by richgel999** [comment]
I've added a new flag "-ktx_only" for you - will go out in v1.16 sometime next week.

**Comment by dpwiz** [comment]
Is a part of v1.16.4 :tada:
