### ISSUE TITLE
jpgd::jpeg_decoder::check_sample_buf_ofs(int) const: Assertion `ofs >= 0' failed.

### ISSUE THREAD

**Issue by MarkCallow** [BinomialLLC/basis_universal#229]
The attached file passed to `basisu` gets this assertion, only in the Debug configuration of course. The assertion is at line 275 in `jpgd.h` called from line 2020 in `jpgd.cpp`.

![body_texture](https://user-images.githubusercontent.com/2244683/115977477-847fa000-a52d-11eb-94ec-26c7fa154b97.jpg)

**Comment by richgel999** [comment]
got it - I'll check it out

**Comment by kanerogers** [comment]
Hi there! Any update on this one?

**Comment by richgel999** [comment]
Looking at it today - stand by.

**Comment by richgel999** [comment]
Fix is incoming - very simple.

**Comment by richgel999** [comment]
Fix is up. BTW - we don't really want to be maintaining our own fuzzed JPEG reader. We're going to try replacing it with something else, but the question is what.
