### ISSUE TITLE
Compile warning with VS2019 warning level 4 (/W4)

### ISSUE THREAD

**Issue by MarkCallow** [BinomialLLC/basis_universal#230]
I just upped my VC++ warning level to 4. There is 1 warning in basisu_transcoder.cpp at line 17339

```
'pComp_data': local variable is initialized but not referenced.
```

Please make this trivial fix (remove the line) so your code compiles cleanly.

It's great there is only 1 warning. Even better if there were none.

**Comment by MarkCallow** [comment]
There's one more that clang reports but VS2019 doesn't. Strange. It is `transcode_alpha_data_to_opaque_formats` at line 10781.

**Comment by MarkCallow** [comment]
And one more in the encoder `bytes_per_line` at line 1782 in basisu_enc.cpp.

**Comment by richgel999** [comment]
ok - got it thanks.
