### ISSUE TITLE
How to play *.basis video in THREE

### ISSUE THREAD

**Issue by yomomano** [BinomialLLC/basis_universal#246]
We are converting our videos to images sequences and basis-video . we can load the video in THREE JS but dont really see how to play/pause the video . Must we make our own video controller in the animation loop or is there a better solution somewhere?

Thanks !

**Comment by kenrussell** [comment]
.basis videos have to be manually redrawn; they don't load into HTMLVideoElements, and that's how Three's video textures work. It'll be necessary to write your own video controller. Suggest you raise an issue on https://github.com/mrdoob/three.js - or even better put up a pull request if you get it working. :)

**Comment by yomomano** [comment]
Alrighty. So i made a very rough controller inside the THREE BasisTextureLoader.js from THREE and manage to transcode different frames of a basis file to a texture by providing the frame index in function basisFile.transcodeImage(...) (2nd arg is frame index) .  See code snippet below how i do it.

However only frame 0 looks good, all others are weird. See two images (blue is renderer background, only black is part of texture). 

frame 0:
![frame0](https://user-images.githubusercontent.com/3234364/126595573-235b81d3-e8aa-4560-8887-313f94556c73.JPG)
frame N
![frameN](https://user-images.githubusercontent.com/3234364/126595574-1ec4021b-103b-4f06-ac58-d80eb6f1cf83.JPG)

The basis animation (with alpha) is made with basisu.exe providing a sequence of uncompressed TGA files (with alpha) as in:

`basisu.exe -tex_type video  -max_selectors 8192 -max_endpoints 8192 -framerate 25 -multifile_num 5 -multifile_printf "x%04u.tga"`

Is there something I do wrong in this command line?

Or do I transcode the frame incorrectly (see below code) ?

Some background for all this: we are making a texture-heavy webGL app to be run on Quest 2 standalone. Compressed textures are essential due to its limited graphics. we are trying to find a way to play acceptable resolution video on a mesh. Normal MP4 video texture kills the Quest 2 when video is more than a few megs. I am open to alternatives for Basis videos if you know !

Thanks !

== snippet from THREE BasisTextureLoader.js with frameIndex ==

```
      const basisFile = new BasisModule.BasisFile(new Uint8Array(buffer)); // full buffer loaded from *.basis file
      const basisFormat = basisFile.isUASTC() ? BasisFormat.UASTC_4x4 : BasisFormat.ETC1S;
      const width = basisFile.getImageWidth(0, 0);
      const height = basisFile.getImageHeight(0, 0);
      const levels = basisFile.getNumLevels(0);
      const frameCount = basisFile.getNumImages();
      const hasAlpha = basisFile.getHasAlpha();
      let mip = 0; // mipmap index, we only have one
      const mipWidth = basisFile.getImageWidth(0, mip);
      const mipHeight = basisFile.getImageHeight(0, mip);
      const dst = new Uint8Array(basisFile.getImageTranscodedSizeInBytes(0, mip, transcoderFormat));
      const isVideo = frameCount > 1;
      const status = basisFile.transcodeImage(
        dst, // data to be used in mipmaps array of texture
        frameIndex, // index provided by caller
        mip, // mip index
        transcoderFormat,
        isVideo,
        hasAlpha
      );
```

**Comment by kenrussell** [comment]
Have you tried drawing the result into a 2D canvas context for debugging? This would eliminate the possibility of something going wrong in your shaders, geometry, blending modes, etc.

**Comment by yomomano** [comment]
yeah tried that. first frame looks as expected. this would also look off if the cause is in shader or so i'd expect.
also, tried the sample basis video file included in the repos (kodim18.basis) and here all frames look normal. so my guess it is the encoding of the tga files into basis video file. 

open to any ideas/trials that can lead me to a solution. would hate to abandon basis due to maybe just a detail...

**Comment by richgel999** [comment]
"Is there something I do wrong in this command line?"

Your command line looks reasonable to me. Can you unpack the video to individual frames using the command line tool? (There's also an old but still functional video test app in the webgl_videotest directory which I use for testing.)

**Comment by yomomano** [comment]
Thanks for you answers!

"the resulting .KTX and .PNG files look reasonable" --> yes, looking perfectly normal. Attached a 5-frame sample for reference.

[TGA_ALPHA_5frames.zip](https://github.com/BinomialLLC/basis_universal/files/6883049/TGA_ALPHA_5frames.zip)

"You must unpack the video from the first frame to the last" --> can you pls indicate how i do that? say, i want frame 5 and i have the byte buffer from the basis file: isnt it just using 'basisFile.transcodeImage(..., frameindex,...)' ? 

Thanks !

**Comment by richgel999** [comment]
> "You must unpack the video from the first frame to the last" --> can you pls indicate how i do that? say, i want frame 5 and i have the byte buffer from the basis file: isnt it just using 'basisFile.transcodeImage(..., frameindex,...)' ?

The frameIndex must always start at 0, and on every call it must only be incremented by 1. You can't skip any frames. If you want frame 5, you must unpack frames 0-4 first. This limitation is for "video" texture types explicitly - texture arrays support random seeking, but aren't compressed as well (due to no skip blocks). This is not a limitation of the KTX2/.basis file format, but the current encoder which will be improved after we get through another major milestone (encoder optimization/compute shader support).

**Comment by richgel999** [comment]
Looks like this is resolved - please let me know if you need any more help on this.
