### ISSUE TITLE
The transcoder & the KDFS do not agree on the ETC1S flip bit

### ISSUE THREAD

**Issue by lexaknyazev** [BinomialLLC/basis_universal#254]
From the KDFS:
> Finally, the _flip bit_ is encoded as 0 — the subsets are identical anyway.

Source code here:
https://github.com/BinomialLLC/basis_universal/blob/b993de420914a9f710e02655ccda6a20ee3112d6/transcoder/basisu_transcoder.cpp#L7983

/cc @fluppeteer @MarkCallow

**Comment by richgel999** [comment]
This slipped between the cracks. It shouldn't matter to Basis Universal - so I can disable it on my end.
