### ISSUE TITLE
Inconsistencies with handling empty Huffman tables

### ISSUE THREAD

**Issue by lexaknyazev** [BinomialLLC/basis_universal#261]
In general, Huffman tables cannot be empty. This is enforced by the following checks in `basisu_lowlevel_etc1s_transcoder::decode_palettes` and `basisu_lowlevel_etc1s_transcoder::decode_tables`.

https://github.com/BinomialLLC/basis_universal/blob/646a9f826131cb0b9e14b5e4740874808315f83a/transcoder/basisu_transcoder.cpp#L7585-L7588

https://github.com/BinomialLLC/basis_universal/blob/646a9f826131cb0b9e14b5e4740874808315f83a/transcoder/basisu_transcoder.cpp#L7859-L7862

https://github.com/BinomialLLC/basis_universal/blob/646a9f826131cb0b9e14b5e4740874808315f83a/transcoder/basisu_transcoder.cpp#L7871-L7874

https://github.com/BinomialLLC/basis_universal/blob/646a9f826131cb0b9e14b5e4740874808315f83a/transcoder/basisu_transcoder.cpp#L7883-L7886

https://github.com/BinomialLLC/basis_universal/blob/646a9f826131cb0b9e14b5e4740874808315f83a/transcoder/basisu_transcoder.cpp#L7895-L7898

However in one case, there is a special micro-optimization that allows an empty `delta_selector_pal_model` table when there is only one entry in the selector codebook:

https://github.com/BinomialLLC/basis_universal/blob/646a9f826131cb0b9e14b5e4740874808315f83a/transcoder/basisu_transcoder.cpp#L7799-L7802

---

1. The latter optimization is not aligned with the encoder's behavior since it seems to always make that table non-empty:
https://github.com/BinomialLLC/basis_universal/blob/646a9f826131cb0b9e14b5e4740874808315f83a/encoder/basisu_backend.cpp#L1703-L1704

2. On the other hand, a few more tables may benefit from being empty in some cases. Namely,
   - One or two of three endpoint color delta tables could be empty when the actual delta values don't need them.
   - `m_selector_history_buf_rle_model` could be empty when the history buffer is always used literally, i.e., without RLE.

**Comment by richgel999** [comment]
Thank you - these are all excellent points. I'll need to go over this with a fine tooth comb and document this behavior.

**Comment by richgel999** [comment]
OK - I don't want to change the encoder to produce empty tables. This is too risky/complex for little if any practical or useful gain.
I'm fine with this being in the spec - they shouldn't be empty.
