### ISSUE TITLE
Request for help with installation

### ISSUE THREAD

**Issue by tomthebearded** [BinomialLLC/basis_universal#266]
Hi,
i'm using a mac ( for the first time) and i'm having some problems with the installation of basis.
I've downloaded the project's folder and runned the command cmake "CMakeLists.txt" and "make" from the terminal following the READ.me instructions.
At the end i get the message [100%] Built target basisu.
After that if i try the command basisu i get the error "command not found".

Am i missing something?

Thank you

**Comment by ismacaulay** [comment]
It should be in the `bin_osx` directory, so if you change to that directory then you can run it with `./basisu`. If you want to install it, you can use `make install` which will then install it to `/usr/local/bin` and you should then be able to run `basisu`

**Comment by richgel999** [comment]
Yes, look in the bin_osx directly. Let me know if you have any other problems.

**Comment by tomthebearded** [comment]
Thank you both
