### ISSUE TITLE
The encoded basis file is different on macOS and Ubuntu

### ISSUE THREAD

**Issue by ismacaulay** [BinomialLLC/basis_universal#267]
Hi, 

I am experimenting with basis universal, and came across an unexpected behaviour where the generated .basis file is not the same between macOS 11.6 and Ubuntu 20.04. The resulting basis file on Ubuntu is 9 bytes larger. I am curious if this is expected. 

Some notes:
- Both cli tools have been compiled the same with Debug flags turned on
    - macOS is using clang 13.0.0, Ubuntu is using gcc 9.3.0
- Both are using the exact same png file
- Both are running with the command `basisu image.png`

Further investigation makes it appear that the transcoded image produced by both basis files are also not the same. Again, this was a bit unexpected to me as I would have assumed that the basisu tool would produce the same output regardless of platform when given the same input png.

If this is expected behaviour then great, otherwise I am happy to provide any addition information needed to help debug

Thanks

**Comment by richgel999** [comment]
Yes, this is expected. You would have to use the same compilers on each platform. Unfortunately, our customers use a lot of floating point calculations, and the various compilers output slightly different optimized code.
