### ISSUE TITLE
-output_file is ignored

### ISSUE THREAD

**Issue by Akaricchi** [BinomialLLC/basis_universal#284]
Since 1.16, use cases like `basisu -file input.png -output_file output.basis` are broken, because `-individual` is now the default and `-output_file` is ignored in that mode. `-tex_array` works around the problem, but this is not only a breaking change but also a really bad and counter-intuitive UI design. I think `-tex_array` should be the default, at least when only a single file name is passed. `-output_file` should probably error out in `-individual` mode to avoid confusion.

**Comment by richgel999** [comment]
Fix is checked in. Thanks for the report! Will push out a new EXE tonight.
