### ISSUE TITLE
Unpacker produces non-valid KTX files

### ISSUE THREAD

**Issue by MikuAuahDark** [BinomialLLC/basis_universal#286]
According to https://www.khronos.org/registry/KTX/specs/1.0/ktxspec_v1.html, for compressed textures, `glTypeSize` must be set to 1, but currently all transcoded texture set this to 0.

> ### `glTypeSize`
> `glTypeSize` specifies the data type size that should be used when endianness conversion is required for the texture data stored in the file. If `glType` is not 0, this should be the size in bytes corresponding to glType. For texture data which does not depend on platform endianness, **including compressed texture data**, `glTypeSize` must equal 1.

I discovered this when `astcenc` decoder complains of the resulting ASTC KTX file is invalid so I wrote simple Lua script to extract the KTX header information and found these.

**Comment by richgel999** [comment]
Got it - will fix. Thanks for the report!
