### ISSUE TITLE
Mipmapped array textures stored incorrectly in ktx2

### ISSUE THREAD

**Issue by superdump** [BinomialLLC/basis_universal#296]
The KTX2 specification says that the mip array is supposed to be stored from highest mip (lowest resolution) to lowest mip (highest resolution):
https://github.khronos.org/KTX-Specification/#_mip_level_array
The level indices are supposed to be stored from the lowest mip to the highest mip:
https://github.khronos.org/KTX-Specification/#_level_index
And within the data for any one mip level, the structure of the data is meant to be for each layer, for each cube face, for each z slice of blocks, for each y row of blocks, for each x block:
https://github.khronos.org/KTX-Specification/#levelImages

However, files output from `basisu` using its `-tex_array` option, which seems to be for creating array textures (as in those using 2d array samplers where one has to specify a layer when sampling) stores all mips for the first layer, then all mips for the second, and so on. As such, one has to iterate for each layer, for each mip level, which seems wrong?

**Comment by superdump** [comment]
This also seems to be broken in the `toktx` tool: https://github.com/KhronosGroup/KTX-Software/issues/562

**Comment by superdump** [comment]
I think maybe I spoke too soon. The data does seem to be laid out as mip n layer 0 ... n, mip n-1 layer 0 ... n, etc, but the GPU wants layer 0 mip 0 ... n, layer 1 mip 0 ... n, etc. So when creating the texture buffer, you have to loop over layers, then mip levels.

**Comment by richgel999** [comment]
OK - will investigate. We definitely want to do this correctly.

**Comment by superdump** [comment]
This could well be an error on my part when uploading data to the GPU. I am currently building a contiguous buffer of the mip and layer data and uploading it in one go. When doing that, this M1 Max seems to need the data in layer 0 mip 0..n, layer 1 mip 0..n order.

**Comment by richgel999** [comment]
It's unlikely both toktx, basisu, and the KTX2 validator do this incorrectly (but not impossible).

**Comment by alecazam** [comment]
Every api has it’s own order.  Some want mip order, and some want array order.  None want the order ktx2 uses which is smallest mips first.  KTX was closer to ideal, but three sword sizes in which threw off block alignment.  Metal doesn’t even have an SPI construct to upload more than one face/slice at a time.  Just decompress/transcode and copy to a staging buffer with block alignment.  Then gpu upload.

**Comment by superdump** [comment]
I agree with closing the issue. Sorry for the noise. I thought I had understood something but it turned out it was rather a graphics API issue.
