### ISSUE TITLE
Support file path with unicode characters

### ISSUE THREAD

**Issue by Ben-Mack** [BinomialLLC/basis_universal#297]
Basisu doesn't work if path contain unicode character:

```
> basisu "D:\TEMP\漢字\normal.png"

Basis Universal GPU Texture Compressor v1.16.3
Copyright (C) 2019-2022 Binomial LLC, All rights reserved
Using SSE 4.1: 1, Multithreading: 1, Zstandard support: 1, OpenCL: 0
Processing 1 total file(s)
Processing source file "D:\TEMP\??\normal.png"
ERROR: load_png: Failed reading file "D:\TEMP\??\normal.png"!
ERROR: Failed reading source image: D:\TEMP\??\normal.png
ERROR: Compressor failed reading a source image!
```

Hope this bug will be fixed soon.

**Comment by richgel999** [comment]
Got it. Will fix.

**Comment by e-dant** [comment]
Here are some helper functions that might work:

https://github.com/e-dant/watcher/blob/next/include/watcher/adapter/windows/watch.hpp

**Comment by Ben-Mack** [comment]
@richgel999 Hope this will be fixed soon. Some users of mine having problem because they have non-latin char in Windows user folder name.

**Comment by richgel999** [comment]
Got it- I've got fixes coming. Been working on this.
