### ISSUE TITLE
vector: malloc() failed allocating with large input image & limited memory

### ISSUE THREAD

**Issue by h4k1m0u** [BinomialLLC/basis_universal#304]
When I try to convert a relatively large jpg image of 6016x4000 pixels to ktx2 format (see command below) on a slow machine with only 2G of RAM I get the following error (I've built basisu from source):

```
vector: malloc() failed allocating 75497472 bytesAborted
```

The command run on Debian shell:

```
$ ./basisu image.jpg -ktx2
```

The return code from the script is: 134 (SIGABRT) which I guess was due to my limited memory.
Is there a way to bypass this error?

**Comment by richgel999** [comment]
"Is there a way to bypass this error?"
Hmm - with only 2GB of RAM there's not much I think we could do (for such a large image). Is it possible to run it as a 64-bit process with virtual memory?

**Comment by h4k1m0u** [comment]
Sorry for the delay.
No idea, I've never used virtual memory before for any kind of processing.
I guess I'll close this issue since the easier way to avoid it is to simply limit the size of the image to convert.
