### ISSUE TITLE
Two versions of transcoder???

### ISSUE THREAD

**Issue by jiapei-nexera** [BinomialLLC/basis_universal#314]
[contrib_previewers_basisu_transcoder](https://github.com/BinomialLLC/basis_universal/blob/master/contrib/previewers/lib/basisu_transcoder.cpp) vs. [transcoder_basisu_transcoder](https://github.com/BinomialLLC/basis_universal/blob/master/transcoder/basisu_transcoder.cpp)

**Comment by cwoffenden** [comment]
The one in `contrib` is tied to the windows preview tool and is committed amalgamated and standalone so as not to need updates to the previewer if the main source changes. The one you want is in:

https://github.com/BinomialLLC/basis_universal/tree/master/transcoder

**Comment by richgel999** [comment]
Yes, that's correct. You want the files in "transcoder".
