### ISSUE TITLE
Difference between -level & -q options

### ISSUE THREAD

**Issue by Makio64** [BinomialLLC/basis_universal#33]
Whats the difference between -q & -level options ?

From the README  they both increase the quality of the output but whats their exact function and are they compatibles ?

Thanks!

**Comment by richgel999** [comment]
Hi - "-level X" enables/disables a bunch of encoder stages that generally increase quality (usually slightly) at the expense of large amounts of CPU time. The larger the level, the slower the encoder goes, but quality doesn't improve much beyond level 2/3. Level 0 is fastest but is too low quality for many uses. Changing this option doesn't change the bitrate or compression efficiency much, if at all.

"-q X" is the main quality knob, like with JPEG's quality level. It controls the codebook sizes used to quantize the compressed texture. Larger codebooks increase the quality a lot, but also increase the bitrate. This is the main knob you use to control the quality vs. bitrate tradeoff. Larger codebooks also increase compression time.

For the most part, I suspect the two most useful quality levels are 1 and 2, and possibly 3. Level 0 is currently iffy from a quality perspective, and levels beyond 2/3 are too slow to be practical. We're aiming for level 1 (the default) to be fine in almost all scenarios.

Hope that helps.

**Comment by richgel999** [comment]
So basically, just change the "q" option to dial in the desired bitrate vs. quality tradeoff. If you are desperate and must have faster encoding, try level 0. If you really need even higher quality, try level 2 or 3.

Note that the encoder converts the -q setting to endpoint/selector codebook sizes. If you want to directly control these codebook sizes yourself, use -max_selectors X and -max_endpoints X.

**Comment by Makio64** [comment]
Thanks for all the explanations, very clear & useful !
It would be nice to add it in the README for other users
