### ISSUE TITLE
SSE4.1 support cannot be enabled on machines with AVX

### ISSUE THREAD

**Issue by stefantalpalaru** [BinomialLLC/basis_universal#342]
It is due to this check:

https://github.com/BinomialLLC/basis_universal/blob/8903f6d69849fd782b72a551a4dd04a264434e20/encoder/basisu_kernels_sse.cpp#L26-L27

Looks like some unfortunate refactoring artefact from old code that supported more than one SIMD type.

**Comment by richgel999** [comment]
If __AVX__ || __AVX2__ || __AVX512F__ are defined here then the generated SSE code won't execute on very old (ancient!) CPU's that don't support AVX. That's why these macros are here. I'll double check that this still works, though.

**Comment by richgel999** [comment]
I've verified that SSE supports works as intended under Windows and Linux. Can you describe what you're doing that's causing these code gen sanity checks to trigger? Your options are probably not the same as the ones used to compile the tool.
I think it's fine to remove them if you're ok with the generated code not working on old CPU's. Perhaps I can put these checks in a guard.
