### ISSUE TITLE
Will OpenCL 3.0 improve compression performance?

### ISSUE THREAD

**Issue by happyhackingkksk** [BinomialLLC/basis_universal#349]
I'm running basisu.exe -parallel -opencl -file to compress dozens JPEG with 6000x4000 resolution to BASIS, GTX1050Ti's CUDA only works intermittently, and compared to compression without opencl, the time only reduce by about 20%.
And it seems that the acceleration effect of OpenCL is only effective for images with relatively high resolutions, it's even faster to not use OpenCL for images with a resolution of 1500x1000.
I don't know why and wonder if modify the OpenCL-related code to support OpenCL 3.0, will it improve the compression performance? 
Thank you.

**Comment by richgel999** [comment]
OpenCL performance vs. the CPU highly depends on the driver, the GPU and the CPU, etc. I doubt OpenCL 3.0 would help. There are more optimizations I could do, but it's a lot of work.
