### ISSUE TITLE
Heavy banding compressing several files in one (cubemap)

### ISSUE THREAD

**Issue by MotivaCG** [BinomialLLC/basis_universal#35]
Reference:
![noga_0000_px](https://user-images.githubusercontent.com/7759954/59532425-fd9d1d80-8ee8-11e9-9eec-8828f0c3fd32.png)

Compressed and decompressed
![noga_0000_px_unpacked_rgb_BC1_0_0](https://user-images.githubusercontent.com/7759954/59532464-1c031900-8ee9-11e9-933f-f9ec08c68861.png)

Any thought on this?

**Comment by richgel999** [comment]
Hi - I compressed the above image a few ways using the latest code, using various -q and -level settings, and here are the results. I also viewed the .basis file using the WebGL viewer (which uses the GPU to decode the BC1 data), and it doesn't appear banded. What version of Basis did you use? What are your exact settings? How did you unpack the compressed texture data?

Default options BC1:
![59532425-fd9d1d80-8ee8-11e9-9eec-8828f0c3fd32_unpacked_rgb_BC1_0000](https://user-images.githubusercontent.com/6934809/59643966-b51b7500-911f-11e9-9a14-180be21e5ecd.png)

-q 255 BC1:
![59532425-fd9d1d80-8ee8-11e9-9eec-8828f0c3fd32_unpacked_rgb_BC1_0000](https://user-images.githubusercontent.com/6934809/59643995-dd0ad880-911f-11e9-9cce-f213f9565b9e.png)

-q 255 -level 2 ETC1:
![59532425-fd9d1d80-8ee8-11e9-9eec-8828f0c3fd32_unpacked_rgb_ETC1_0000](https://user-images.githubusercontent.com/6934809/59644190-b7320380-9120-11e9-918b-0c495e6ef0fe.png)

**Comment by richgel999** [comment]
Okay, I think (and hope) you are looking at the transcoder's PVRTC1 4bpp output. Here's what I get. Unfortunately, PVRTV1 is a difficult to handle format, especially in real-time. I compared the output from Basis vs. PVRTexTool, and it's a little lower than "Normal" quality (and far better than "Fast").

Right now, this is about as good as it gets with PVRTC1 (with Basis). I have some ideas on how to increase PVRTC1 quality (I have a prototype of very high quality encoder), but it'll be later this year before I can try them.

![59532425-fd9d1d80-8ee8-11e9-9eec-8828f0c3fd32_unpacked_rgb_PVRTC1_4_OPAQUE_ONLY_0000](https://user-images.githubusercontent.com/6934809/59644436-bb125580-9121-11e9-9b93-06231fa84adc.png)

**Comment by richgel999** [comment]
If I added a slower PVRTC1 option to the transcoder which fixed this banding, would you use it? It would be several times slower.

**Comment by MotivaCG** [comment]
Probably I didn't explain properly, I had this kind of issues ONLY if I package 6 images (faces of a cubemap) in a single file, using only one image per file it works like a charm.

Today I'm on a travel but hopefully I'll be able to upload the 6 images tomorrow for testing.

Regards, Victor

**Comment by richgel999** [comment]
Did you increase the quality level to compensate? Try "-q 255", or "-max_selectors 16128 -max_endpoints 16128".

**Comment by MotivaCG** [comment]
Concerning your own compression please note this artifacts:
![image](https://user-images.githubusercontent.com/7759954/59744834-b3fb5c80-9273-11e9-9d74-7255ea8e4a5f.png)

**Comment by MotivaCG** [comment]
[pngcube.zip](https://github.com/BinomialLLC/basis_universal/files/3304891/pngcube.zip)
And these are the 6 cube faces, still that heavy banding appears using (much worse than compressing them image by image)

> basisu.exe -file noga_0000_px.png -file noga_0000_nx.png -file noga_0000_py.png -file noga_0000_ny.png -file noga_0000_pz.png -file noga_0000_nz.png -q 255

**Comment by Makio64** [comment]
@richgel999 if there was an option for slower but much higher quality on pvrtc1, i would definitively use it

**Comment by RandomShaper** [comment]
@MotivaCG, are you by the way using `-mip_renorm`?
I think there's a bug with it, at least when using it together with `-seperate_rg_to_color_alpha`.
What happens is that mip levels >= 1 get "posterized", like reduced to 16 colors or something.

**Comment by RandomShaper** [comment]
Now I realize that probably has nothing to do. `-mip_renorm` works on normal maps and you are getting the banding in color.

**Comment by nh2** [comment]
> If I added a slower PVRTC1 option to the transcoder which fixed this banding, would you use it? It would be several times slower.

@richgel999 We would love this most likely for our app.

The banding for us is so strong that we can't really use it for iOS over PVRTexToolCLI (also for photos of flats, like the above).

Just for clarification, would it be slower on the creation side, or on the Basis->PVRTC side (e.g. on the iOS device)?

**Comment by richgel999** [comment]
> Just for clarification, would it be slower on the creation side, or on the Basis->PVRTC side (e.g. on the iOS device)?

It would be slower on the Basis->PVRTC side (on the iOS device). What we would do is bring in some of the new offline table-based algorithms we developed for PVRTC1 last year and add them to the transcoder. I believe the key ones are simple enough to do in real-time. I would expect transcoding to be perhaps 30-50% slower in this mode, but the banding artifacts would go *way* down.

This would cost approx. 64K-128K extra RAM to hold the precomputed tables.

Would this be useful to you? Honestly, we really want to do it, because it'll make PVRTC1 look tons better. At first, it would only be used on RGB textures, then we could do it on alpha textures.

**Comment by richgel999** [comment]
Also, Basis supports ASTC now, and most iOS devices support ASTC. (Although WebKit on iOS doesn't yet, sadly!) So if you can switch to ASTC on iOS, the problem is a moot point. On devices which don't support ASTC, you could use 565 or half-res 32bpp.

**Comment by Makio64** [comment]
I will personnaly use it. Priority for most of my client is too get high quality no matter the decompression time, if .basis cant reach the same quality than .pvrtc we cant using it.

**Comment by nh2** [comment]
> Would this be useful to you?

@richgel999 Absolutely!

As long as it remains reasonably real-time (for us: can be used to build up a WebGL scene with textures loaded over the Internet), we'd definitely use it. 50% time increase sounds like no problem at all for our use case.

> This would cost approx. 64K-128K extra RAM to hold the precomputed tables.

Fine for us: The iOS devices we need this for have GBs of RAM.

> At first, it would only be used on RGB textures, then we could do it on alpha textures.

We don't use alpha currently, so that's fine as well.

> [ASTC] Although WebKit on iOS doesn't yet, sadly

We need WebGL, so unfortunately we can't use ASTC.

> the banding artifacts would go _way_ down
> it'll make PVRTC1 look tons better

:heart: 

We'd be extremely happy to use this.

**Comment by MotivaCG** [comment]
I'll use it for sure!

**Comment by MotivaCG** [comment]
I'm wondering if any of these ideas were implemented

**Comment by richgel999** [comment]
The UASTC update, coming in a few hours today, gives you more options in terms of quality.

**Comment by nh2** [comment]
> The UASTC update

@richgel999 That's https://opensource.googleblog.com/2020/03/google-and-binomial-partner-to-open.html, right?

> gives you more options in terms of quality

Could you update us here on the new options in relation to colour banding?

This and #78 are the 2 big things holding us back to use Basis for all devices.

**Comment by richgel999** [comment]
We may increase PVRTC1 quality in the future, but it will slow down transcoding. For now, PVRTC1 is usable for a wide range of textures, but it's probably weakest with gradients. For textures like this you may want to transcode to half-res using 32bpp or possibly 565, which the transcoder supports.
