### ISSUE TITLE
Does this project with WebGPU (web)?

### ISSUE THREAD

**Issue by shi-yan** [BinomialLLC/basis_universal#362]
I saw the webgl/wasm demo, but could you confirm if this works with webgpu? i.e. if the transcoding step happens on GPU and relies on webgl?

The reason for asking is because of the paper referenced in README:

```
However, decoding the texture on the CPU eschews the main benefits of compressing textures: the gained bandwidth across the CPU-GPU bus.
...
In this paper, we present a new supercompression algorithm GST, pronounced jist, for decompressing textures on the GPU into
hardware-compressed formats.
```

The above seems to suggest a GPU based transcoding. Since this library predates the WebGPU era, I wonder if it works with it.

**Comment by richgel999** [comment]
The transcoder is entirely CPU. There is no GPU transcoder yet.
