### ISSUE TITLE
losinglena.com domain expired

### ISSUE THREAD

**Issue by CosmicHorrorDev** [BinomialLLC/basis_universal#364]
The domain linked in the README has expired and now acts as a _For Sale_ sign for the domain. Not sure if there is another link that could replace it or what, but figured I would give you all a heads up

https://github.com/BinomialLLC/basis_universal/blob/ad9386a4a1cf2a248f7bbd45f543a7448db15267/README.md?plain=1#L27-L31

**Comment by richgel999** [comment]
Thanks, I'll redirect that to archive.org.
