### ISSUE TITLE
Remove reference to etc1_global_selector_codebook from transcoder wiki page

### ISSUE THREAD

**Issue by SafariMonkey** [BinomialLLC/basis_universal#367]
I was trying to use the transcoder, and I was using the wiki found here:

https://github.com/BinomialLLC/basis_universal/wiki/How-to-Use-and-Configure-the-Transcoder

which has the following section:

> Also, ideally once at startup, you need to create a single instance of the `basist::etc1_global_selector_codebook` class, like this:

> `basist::etc1_global_selector_codebook sel_codebook(basist::g_global_selector_cb_size, basist::g_global_selector_cb);`

This did not compile, so I looked at the repo history and saw that `etc1_global_selector_codebook` was removed almost everywhere in commit deeb5ac.

> ..., removing global selector palette code (it was unused/dead code), ...

I would suggest removing the line from the wiki, as while it's easy on first compile to tell that it doesn't work, figuring out whether one must do something else instead can take some time. (My interpretation after reading through that commit is that there is no replacement operation necessary.)

**Comment by tim-rex** [comment]
Duplicate of #365, though this issue is probably more descriptive

**Comment by SafariMonkey** [comment]
@tim-rex Oh, thanks! I searched for "etc1_global_selector_codebook" and when I got no results I assumed there wasn't an issue yet. This has a "mentioned" link there now, so if there is value in the description it won't be lost. I'll close this.
