### ISSUE TITLE
Does each transcoder only work with one basis file ?

### ISSUE THREAD

**Issue by Nhan1989** [BinomialLLC/basis_universal#38]
Hello everyone, I'm trying integrate Basis Universal to my app. My data has many basis files (each basis contains many images). My approach is use only one transcoder, then call transcoder->start_transcoding (...) each time I want to get the texturefrom different Basis file but the transcoder only work with the first Basis data which i set to it via start_transcoding method. 
So the question is:
1. Did the transcoder work as intented or i missing some steps ?
2. If one transcoder work with only one basis, so create multi transcoder and code book each time a texture was called may impact to performance ? Especialy when i use one texture to one basis (compression multi textures to one basis is killing my pc).

Thank you for support.

**Comment by kg** [comment]
I would suggest just using one transcoder per file. You can reuse a single codebook instance for all your transcoders as suggested in the README and that seems to work just fine. In my testing I'm creating a new transcoder per file and my performance is just fine, much better than loading PNGs or JPEGs, so I would not worry about transcoder overhead unless it is showing up in your CPU profiles.

Hope this helps.

**Comment by Nhan1989** [comment]
Thank you very much for quick reply **kg** . I'll make as your suggestion.

**Comment by richgel999** [comment]
The original (intended) design was that you would instantiate a new transcoder for each .basis file you want to transcode. Once you call start_transcoding(), you have basically "locked" in that instance of the transcoder to a single .basis file.

An alternative is to compress all your textures (or large groups of them) to a single large .basis file, using large codebook (use "-max_selectors 16128 -max_endpoints 16128"). Then you can use a single transcoder to access a large set of images/mip levels.
