### ISSUE TITLE
Headers and DFDs for Basis HDR in KTX2

### ISSUE THREAD

**Issue by donmccurdy** [BinomialLLC/basis_universal#381]
Hi! I'm testing encoding .exr files to .ktx2 with the updated basisu tool. The resulting .ktx2 image understandably has new header fields, read with `ktx info`  CLI, and I don't recognize a couple of them. These show up as validation warnings but I imagine they're intentional:

```
error-6016: Invalid colorModel in basic DFD block for block compressed VkFormat.
    DFD block #1 colorModel in basic DFD block is (0xA7) but for VkFormat VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK it must be KHR_DF_MODEL_ASTC.
error-6028: Invalid sample in basic DFD block. The samples must match the expected samples of the VkFormat.
    DFD block #1 sample #1 qualifierSigned in basic DFD block is 0 but the expected value is 1 for VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK.
error-6028: Invalid sample in basic DFD block. The samples must match the expected samples of the VkFormat.
    DFD block #1 sample #1 sampleLower in basic DFD block is 0 but the expected value is 3212836864 for VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK.
warning-5004: Non-conformant texture file accepted by libktx.
    KTX 2.0 file does not conform to the specification but it is currently accepted by libktx.
```

Mainly I am wondering – what metadata distinguishes a .ktx2 file with Basis HDR from a .ktx2 file with traditional ASTC? Is that the DFD colorModel field, and/or is the basisu CLI utility setting other new fields that clients/viewers should pay attention to? 

Similarly, I wasn't sure what to make of this line in the help output:

```
-linear: Use linear colorspace metrics (instead of the default sRGB or scaled RGB for HDR), and by default linear (not sRGB) mipmap filtering.
```

What is "scaled RGB" for HDR? The metadata in the encoded KTX2 file suggests Linear Rec. 709 ("Linear sRGB"), just hoping to make sure I'm not missing something there. 

Thank you!

**Comment by richgel999** [comment]
We've been actively working with @MarkCallow at Khronos on the .KTX2 DFD config used by us for UASTC HDR. I _think_ what we're writing is correct according to the KTX2 spec, but Mark would know for sure. I think the KTX2 repo changes to support UASTC HDR are still in progress.

>What is "scaled RGB" for HDR? The metadata in the encoded KTX2 file suggests Linear Rec. 709 ("Linear sRGB"), just hoping to make sure I'm not missing something there.

Normally the UASTC HDR encoder uses scaled RGB colorspace error metrics during lossy compression. The RGB component scales default to (2,3,1). (This is a simple/fast approximation to perceptual error, favoring R and G error more than B.) If you specify the linear flag, it sets the RGB the scales to (1,1,1), so no channel gets favored more.

Note in practice ASTC HDR is fundamentally perceptual. It assumes the RGB components are going to be somewhat to very correlated, and some modes allocate less bits to the B component. So there are limits to how "un-perceptual" we can made UASTC HDR. Also, UASTC HDR only supports a single plane for compatibility with BC6H, so very uncorrelated inputs aren't going to be handled very well. (This is probably excessive info, but there you go.)

**Comment by richgel999** [comment]
> Mainly I am wondering – what metadata distinguishes a .ktx2 file with Basis HDR from a .ktx2 file with traditional ASTC? 

Two things:

1. The KTX2 file's main header's "vk_format" field contains:

const uint32_t KTX2_FORMAT_UASTC_4x4_SFLOAT_BLOCK = 1000066000;
header.m_vk_format = basist::KTX2_FORMAT_UASTC_4x4_SFLOAT_BLOCK;

This is equivalent to VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK (which equals 1000066000), because UASTC HDR data is 100% standard ASTC HDR texture data.

This value is actually just the Vulkan format for ASTC HDR 4x4:
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_texture_compression_astc_hdr.html

See VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK .

2. The UASTC HDR DFD, which is like this (see encoder/basisu.comp). Note this is modified a little by the encoder before it's written:
 
static uint8_t g_ktx2_uastc_hdr_nonalpha_dfd[44] = 
{
	0x2C,0x0,0x0,0x0,		// 0 totalSize
	0x0,0x0,0x0,0x0,		// 1 descriptorType/vendorId
	0x2,0x0,0x28,0x0,		// 2 descriptorBlockSize/versionNumber
	0xA7,0x1,0x1,0x0,		// 3 flags, transferFunction, colorPrimaries, colorModel
	0x3,0x3,0x0,0x0,		// 4 texelBlockDimension0-texelBlockDimension3
	0x10,0x0,0x0,0x0,		// 5 bytesPlane0-bytesPlane3
	0x0,0x0,0x0,0x0,		// 6 bytesPlane4-bytesPlane7
	0x0,0x0,0x7F,0x80,		// 7 bitLength/bitOffset/channelType and Qualifer flags (KHR_DF_SAMPLE_DATATYPE_FLOAT etc.)
	0x0,0x0,0x0,0x0,		// 8 samplePosition0-samplePosition3
	0x0,0x0,0x0,0x0,		// 9 sampleLower (0.0)
	0x00, 0x00, 0x80, 0x3F  // 10 sampleHigher (1.0)
};

The DFD may be changed by Mark etc. - I can quickly modify it to whatever it needs to be.

**Comment by MarkCallow** [comment]
@donmccurdy, UASTC HDR is distinguished by the colorModel field of the DFD as @richgel999 noted. The DFD also differs from that of standard ASTC in other small ways. The colorModel is the important one. Adding this to the KTX and Khronos Data Format specifications is a work in progress. See https://github.com/KhronosGroup/KTX-Specification/pull/216. Work on changes to KTX-Software has not yet started. Khronos is preparing an RFP.
