### ISSUE TITLE
transcode_image_level() doesnt work in parallel loading of textures

### ISSUE THREAD

**Issue by tigrazone** [BinomialLLC/basis_universal#382]
Hello.
I try to load ktx2 in parallel and use [code of Sascha Willems](https://github.com/SaschaWillems/Vulkan-glTF-PBR.git)
and code similar as [code from VulkanglTFModel.cpp](https://github.com/SaschaWillems/Vulkan-glTF-PBR/blob/master/base/VulkanglTFModel.cpp)

My code [stops here](
https://github.com/tigrazone/gkNextRenderer-my-private/blob/de4b5ad78a86ca864ffe2fa15cdef4edfc500110/src/Assets/Texture.cpp#L396) and doesnt load ktx2

Can you help to fix it?

**Comment by richgel999** [comment]
Sure - what format are you using? The transcoder should be thread safe. (I will add examples of this in the next release.)

**Comment by tigrazone** [comment]
I can't disable threafs. I need it. I use for ktx2 decoding

**Comment by richgel999** [comment]
> I can't disable threads. I need it. I use for ktx2 decoding

Can you please temporarily disable threading and see if the problem goes away. If it doesn't go away, then it's likely not threading related.

**Comment by tigrazone** [comment]
I do on #define BASISU_FORCE_DEVEL_MESSAGES 1
and I see I forget to call
basist::basisu_transcoder_init();
Reread sources [of Sascha Willems](https://github.com/SaschaWillems/Vulkan-glTF-PBR.git) and add call and now works ok
