### ISSUE TITLE
Basisu for Godot Engine

### ISSUE THREAD

**Issue by fire** [BinomialLLC/basis_universal#4]
Was interested into adding this for the Godot Engine.

How difficult is it to remove the OpenMP dependency and keep multithreading?

Thoughts on Basis for Godot Engine? Best uses?

[Edited] Currently Godot defaults to S3TC.
[Edited] Godot can't use OpenMP.

**Comment by richgel999** [comment]
Hi - There's a C++ compressor class here:
https://github.com/BinomialLLC/basis_universal/blob/master/basisu_comp.h

We are open to alternatives to OpenMP. I think removing it from the compressor would be a mostly mechanical exercise, if we used lambdas and a simple job system. We're not getting good load balancing with OpenMP on larger videos, so I may have to bite the bullet and do it soon. I'll add this to the TODO list.

**Comment by richgel999** [comment]
Also, I've been planning on adding a simple C-style entrypoint to the compressor. I have an implementation that I need to check in.

**Comment by fire** [comment]
I would recommend either supporting c++11 or c++03 for compatibility. This means no c++17 parallel for.

**Comment by richgel999** [comment]
Got it, I'm staying with C++11.

**Comment by richgel999** [comment]
BTW - the transcoder doesn't use OpenMP. It's just the encoder that does. The transcode is pretty vanilla C++03 code (no multithreading).

**Comment by richgel999** [comment]
I have locally eliminated all OpenMP usage from the encoder - I'm testing all the changes now. They'll go in by the end of the week.

**Comment by richgel999** [comment]
Okay, all OpenMP usage is gone. Please let me know if you have any issues.
I'll be adding a C-style API and separating out the encoder into a lib soon. Which will be easy - basisu_tool.cpp is the command line tool, everything else goes into the lib.
