### ISSUE TITLE
The unpacked image quality is not same as original image

### ISSUE THREAD

**Issue by Nhan1989** [BinomialLLC/basis_universal#41]
Hello everyone,
I'm trying to pack my texture to basis format with following option get best quality
`basisu x.png -level 5 -max_endpoints 16128 -max_selectors 16128 -no_selector_rdo -no_endpoint_rdo`
My original texture 
![MyImage](https://user-images.githubusercontent.com/45087349/59843431-c1ebd300-9382-11e9-9e57-af1443b90d4b.png)
Here is unpacked texture for ETC1 format
![highest_quality_unpacked_rgb_ETC1_0_0](https://user-images.githubusercontent.com/45087349/59843536-f5c6f880-9382-11e9-94c3-b2ea998aad0a.png)
As you can see, there is big different on unpacked texture, the color pixel doesn't smooth as original texture.
Any suggestion to get better quanlity texture please?
Thank you.

**Comment by richgel999** [comment]
Hi - Basis Universal internally encodes your texture to a strong subset of the ETC1 lossy compressed texture format. So there's some quality loss inherent in this format, no matter what settings you use. This is a common tradeoff involved with compressed textures, and artists usually find ways of working around it when it's a problem. 

You can try compressing it to BC1 and ETC1 using vendor tools and comparing, just to get an idea of the artifacts involved with this type of texture compression.
