### ISSUE TITLE
Are these printfs intentionally not debug_printfs?

### ISSUE THREAD

**Issue by MarkCallow** [BinomialLLC/basis_universal#45]
There are 2 regular `printfs` in `basisu_comp.cpp` one at line 496 that prints "Total basis file slices" and one, a couple of lines later, that prints all the information about each slice. Is it intentional that these are NOT `debug_printf`?

In my use of the compressor from within a library, I'd prefer it did not print anything.

**Comment by richgel999** [comment]
I'll route all printf()'s into some common functions which can be redirected/disabled.

**Comment by richgel999** [comment]
All printf()'s are routed to either debug_printf() or error_printf().
