### ISSUE TITLE
Memory-mapped basis file

### ISSUE THREAD

**Issue by boberfly** [BinomialLLC/basis_universal#5]
Hey!

Great to see this open source! I was just wondering (and maybe there is already support for this) but for very large .basis files, will there be support for the scenario of memory-mapping the .basis file and being able to transcode image slices to memory? I'm thinking about virtual texture scenarios here where each image is a tile/page to load into a physical texture, but you don't want all the compressed files in memory. Maybe it is as easy as passing in an mmap pointer, I haven't tried yet...

Cheers!

**Comment by richgel999** [comment]
Hi - The transcoder just takes pointers to the basis file data (i.e. it doesn't do any file I/O itself). So the user could memory map the file into memory themselves, then pass the pointer to the transcoder API.

**Comment by richgel999** [comment]
I don't think there's any work on our end to enable memory mapped .basis files (you can do this right now).
