### ISSUE TITLE
Assertion failure in basisu_enc.h

### ISSUE THREAD

**Issue by MarkCallow** [BinomialLLC/basis_universal#50]
When compressing https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/FlightHelmet/glTF/FlightHelmet_baseColor.png the assertion at line 1070 in basisu_enc.h fires.

```
assert(node.m_var == var_heap.get_top_priority());
```

However if basisu is compiled without assertions the resulting file appears to be okay at least to casual inspection.

Note that the CMake build, even with `CMAKE_BUILD_TYPE` set to Debug does not appear to include assertions. I verified this by adding `assert(false);` just before line 1070. It doesn't fire. Only in my Xcode Debug build are asserts present.

**Comment by richgel999** [comment]
Ok - I will investigate this. It shouldn't fire, but I would be surprised if this impacts the correctness of the output.

**Comment by rokups** [comment]
This also triggers when trying to compress 4096x4096 image using `-comp_level 5`.

**Comment by richgel999** [comment]
This is fixed.
