### ISSUE TITLE
Alpha support

### ISSUE THREAD

**Issue by bsergean** [BinomialLLC/basis_universal#54]
Hi there,

Thanks so much for trying to solve this problem, which everyone tries to fix in various way.
Apparently alpha support is currently missing, and I wonder if there's any sort of ETA on supporting this. Is that very hard to support ? What would be a good way to start contributing helping here ?

Thanks !

**Comment by toji** [comment]
Alpha is supported by Basis, but not by every transcode target. It's explained in detail in (this section of the repo readme)[https://github.com/BinomialLLC/basis_universal#gpu-texture-format-support-details], but the short version is that ETC1, BC1, BC7, and PVRTC1 don't support alpha channels with Basis. (Yet. Some of them may support it in the future.) If those are the only formats available to your platform, you'll need to decode the alpha channel as a separate greyscale image (with the `cDecodeFlagsTranscodeAlphaDataToOpaqueFormats` flag) and sample it separately in your shaders.

**Comment by sehurlburt** [comment]
Just wanted to let y'all know that alpha will be supported for all formats in the next release, which should be coming out in October if testing goes as planned. No contributions needed (it'd be too many cooks in the kitchen at this point, since it's almost done)-- look forward to release!

**Comment by bsergean** [comment]
Thanks @toji and @sehurlburt for the heads up.

**Comment by bsergean** [comment]
I hope that the alpha support will be at least of beta quality ;)

**Comment by richgel999** [comment]
The .basis format supports alpha channels already, but only a few transcoders can handle outputting alpha: ETC2 EAC and BC3, and BC5. The new ASTC transcoder (which will be released on the next milestone) also supports alpha channels. It also has optimizations for L and LA blocks (for XY normal maps) The next milestone also has transcoders for BC7 alpha (using mode 4) and PVRTC1 4bpp alpha (using a new transcoder).

**Comment by richgel999** [comment]
As the system already supports alpha, I'm closing this bug. The next milestone (due in a few weeks) will have more transcoders supporting alpha.
