### ISSUE TITLE
Feature request:  a standard field for containing some kind of hash of the source image

### ISSUE THREAD

**Issue by jherico** [BinomialLLC/basis_universal#55]
One thing my organization has done with it's use of KTX is ensure that each KTX uses the key/value area to store a hash of the original uncompressed image.  This then ends up becoming the primary key into an in-memory runtime cache of KTX files.  This way if a user is using some kind of asset with embedded images (like an FBX or GLB with inline PNG images), then we can recognize multiple instances of the same input image regardless of their source.  It would be handy if this was a standard field in the binomial format, or the contents of a standard key if arbitrary key/value pairs are supported.

**Comment by richgel999** [comment]
Good idea! We will be extending the format after the next milestone and we'll add this.

**Comment by richgel999** [comment]
We're still going to do this, but we're still defining how exactly .basis files will be extended with extra data without breaking backwards compat.

**Comment by richgel999** [comment]
Hi,
Perhaps this might help: The .basis file format has two fields you can use to hold whatever you want:

basisu::packed_uint<4>      m_userdata0;		// For client use
basisu::packed_uint<4>      m_userdata1;		// For client use

Also, we now completely support KTX2, which supports arbitrary key/value data. Hope that helps. Closing for now - let me know if you think this isn't enough. Thanks!
