### ISSUE TITLE
Feature request: Transcode to uncompressed RGB(A)

### ISSUE THREAD

**Issue by toji** [BinomialLLC/basis_universal#58]
There's a few cases where it would be useful to have the transcoder output uncompressed data (similar to the output of the command line tool with `-unpack`). Specifically, on systems that don't support any alpha-enabled compressed formats (unfortunately common on the web) it may be less disruptive to the existing render pipeline to choose to transcode those images to uncompressed RGBA and use that instead of restructuring the shaders to sample a separate color and alpha image on some platforms.

Obviously that's not optimal from a memory/performance perspective, and you'd get higher quality by using an uncompressed image in the first place, but it would allow more applications to fully switch over to using Basis for ~all their textures without compatibility concerns. Doing so would yield immediate benefits in terms of asset size in almost all cases, and since opaque textures are very common only a small portion of textures would need to use this path.

In addition, it could be a useful debugging tool in some situations (such as if the application's compressed texture rendering path is not functioning as expected.)

**Comment by richgel999** [comment]
Yup, I've been thinking the same thing. I'll add RGBA 32bpp (and maybe 16bpp) options to the transcoder.

**Comment by richgel999** [comment]
The transcoder now directly supports a number of common uncompressed formats:

RGBA 32bpp (R first in memory)
RGB565 16bpp (R at bit position 11)
BGR565 16bpp (R at bit position 0)
RGBA4444 16bpp (R at bit position 12, A at 0)

It unpacks the internal ETC1S data directly to pixels. When outputting raw pixels the transcoder switches to writing plain (standard row by row) raster images, not blocks. 

This code is in the next milestone's build (which I'm sending early this week).

**Comment by toji** [comment]
Wow! Definitely didn't expect that fast of a turnaround time. Thank you!

**Comment by richgel999** [comment]
Thanks - I'm going to add some form of dithering in there as an option.

**Comment by richgel999** [comment]
This is in now!
