### ISSUE TITLE
Compilation and example usage

### ISSUE THREAD

**Issue by hackerb9** [BinomialLLC/basis_universal#6]
While the README is quite extensive, perhaps it should have near the top a section for the impatient which gives the steps for compiling and using it from the command line. Something like
____
## Compilation & Example Usage
    cmake CMakeLists.txt
    make

    bin/basisu samples/kodim20.png        # to convert to basis format
    bin/basisu samples/kodim20.basis      # to extract images from basis

## More detailed examples
* `basisu x.png`
   Compress sRGB image x.png to x.basis using default settings (multiple filenames OK)
* `basisu x.basis`
   Unpack x.basis to PNG/KTX files (multiple filenames OK)
* `basisu -file x.png -mipmap -y_flip`
   Compress a mipmapped x.basis file from an sRGB image named x.png, Y flip each source image
* `basisu -validate -file x.basis`
   Validate x.basis (check header, check file CRC's, attempt to transcode all slices)
* `basisu -unpack -file x.basis`
   Validates, transcodes and unpacks x.basis to mipmapped .KTX and RGB/A .PNG files (transcodes to all supported GPU texture formats)
* `basisu -q 255 -file x.png -mipmap -debug -stats`
   Compress sRGB x.png to x.basis at quality level 255 with compressor debug output/statistics
* `basisu -linear -max_endpoints 16128 -max_selectors 16128 -file x.png`
   Compress non-sRGB x.png to x.basis using the largest supported manually specified codebook sizes
* `basisu -linear -global_sel_pal -no_hybrid_sel_cb -file x.png`
   Compress a non-sRGB image, use virtual selector codebooks for improved compression (but slower encoding)
* `basisu -linear -global_sel_pal -file x.png`
   Compress a non-sRGB image, use hybrid selector codebooks for slightly improved compression (but slower encoding)
* `basisu -tex_type video -framerate 20 -multifile_printf "x%02u.png" -multifile_first 1 -multifile_count 20`
   Compress a 20 sRGB source image video sequence (x01.png, x02.png, x03.png, etc.) to x01.basis
____

P.S. Saw this on Stephanie Hurlburt's twitter and thought I'd take the future for a spin. Looks great so far!

**Comment by aferriss** [comment]
Also it's worth noting that on mac you will have to tell the cmake to use your gcc version. Mine was inside of /usr/local/bin

```
#only if you don't have gcc installed
brew install gcc 

cmake -DCMAKE_CXX_COMPILER=g++-9 CMakeLists.txt
make
```

**Comment by kenrussell** [comment]
Oops, sorry for the noise while I was editing and testing the Markdown.

A pull request is up for review incorporating these suggestions.
