### ISSUE TITLE
Best practice format (desktop) - BC5?

### ISSUE THREAD

**Issue by tim-rex** [BinomialLLC/basis_universal#63]
I'm a bit weak on compressed formats and how they are supported across various API's.. apologies in advance if I've missed the mark

What I _think_ I know...  (in OpenGL speak).. 
  BC1 --> GL_COMPRESSED_RGBA_S3TC_DXT1_EXT
  BC2 --> GL_COMPRESSED_RGBA_S3TC_DXT3_EXT
  BC3 --> GL_COMPRESSED_RGBA_S3TC_DXT5_EXT
  BC5 --> GL_COMPRESSED_SIGNED_RG_RGTC2

What confuses me, is this part of the README:
> Devices/API's supporting BC1-5, BC6H, BC7: Transcode to a single BC5 textures, which used to be called "ATI 3DC". It has two high quality BC4 blocks in there, so it'll look great. Once BC7 alpha support comes online that will be the better option.

I think maybe I have misunderstood the intent of the above.
From what I understand BC5 is a two-channel texture format.  Is there some additional magic to make that work for RGBA?  Rendering a BC5 transcode using GL_COMPRESSED_SIGNED_RG_RGTC2 shows major artefacts.

For now I'm using BC3 and getting good results for RGBA textures.

Incidentally - and probably off-topic...  is there documentation that indicates a mapping between each of the available transcode formats and their corresponding format/enum usage in OpenGL / Vulkan / Metal / etc?

**Comment by tim-rex** [comment]
I've re-read through the readme and discovered that the section I quoted comes under use case #3 titled "For high quality tangent space normal maps"

In context, that all makes sense now - but the indentation of that section of the readme makes this a little bit non-obvious.

I'll leave this ticket open as I think possibly this section of the readme might benefit from some minor formatting.

**Comment by richgel999** [comment]
"Incidentally - and probably off-topic... is there documentation that indicates a mapping between each of the available transcode formats and their corresponding format/enum usage in OpenGL / Vulkan / Metal / etc?"

I'll better document this for OpenGL formats, and others can translate to other API's.

I'll respond in depth to this once the next milestone is shipped.

**Comment by richgel999** [comment]
These should be the proper mappings:

BC1 --> GL_COMPRESSED_RGBA_S3TC_DXT1_EXT
BC2 --> GL_COMPRESSED_RGBA_S3TC_DXT3_EXT
BC3 --> GL_COMPRESSED_RGBA_S3TC_DXT5_EXT
BC4 --> GL_COMPRESSED_RED_RGTC1
BC5 --> GL_COMPRESSED_RG_RTGC2 

Basis Universal doesn't support BC2/DXT3 - it's very rarely used.

BC4 is the same as ATI's ATI1N.
BC5 is the same as ATI's "3DC", or ATI2N, or "DXN".

**Comment by richgel999** [comment]
I've added a table describing which OpenGL enums correspond to each transcoder texture format:
https://github.com/BinomialLLC/basis_universal/wiki/OpenGL-texture-format-enums-table
