### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Zingam** [BinomialLLC/basis_universal#67]
The README is very long, dry and boring to read. I think we could use a chunked, HTML styled tutorial like docs with a TOC and hyperlinks too with some examples, so that relevant information could be searched easily.
It would be nice to see some statistics about what overhead could we expect when using the transcoding over native compression.
Also having some version number at the top of the README would be helpful to notify that a new milestone was released/something has changed.

**Comment by richgel999** [comment]
I'm so sorry the README isn't exciting enough and doesn't meet your very high standards.

**Comment by richgel999** [comment]
I hear you. Better docs are coming!
