### ISSUE TITLE
Artefacts when combining -comp_level 5 -global_sel_pal -no_hybrid_sel_cb (v1.09.00)

### ISSUE THREAD

**Issue by cwoffenden** [BinomialLLC/basis_universal#69]
When compressing this testcard image with `-comp_level 5 -global_sel_pal -no_hybrid_sel_cb`:

![testcard image](https://user-images.githubusercontent.com/8437014/65706191-33c26f80-e08a-11e9-9a95-b9188977970e.png)

The resulting output (created with `-unpack`) is full of black dots in the grey areas:

![black dots](https://user-images.githubusercontent.com/8437014/65706227-4a68c680-e08a-11e9-9642-e5ac84af6ae3.png)

The `.basis` file is here: [testcard.zip](https://github.com/BinomialLLC/basis_universal/files/3658843/testcard.zip) (it's not possible to attach without placing it in a zip). The artefacts are better with the default quality (whereby the dots become a ringing in the grey squares).

**Comment by richgel999** [comment]
I've reproduced this. When the "-global_sel_pal -no_hybrid_sel_cb" options are used, the encoder doesn't use custom selector codebooks at all. Instead, it uses a pure virtual codebook scheme that was intended primarily for small icons (where the overhead of storing a custom codebook can be too large). This method introduces extra noise in the output. Usually it looks fine, but it looks like this test pattern has found an outlier case.

The encoder hasn't been tuned as much when global selector codebooks are enabled like this. I don't think this is a bug, I think it's an genuine compression artifact that is getting amplified by using virtual codebooks. 

Note these artifacts go away when you compress the texture normally, or with "-no_auto_global_sel_pal". We may be disabling automatic usage of global selector codebooks entirely in the future, as it's unclear how useful they actually are to most users and encoding time is noticeably slower.

Is there a particular reason why you are forcing global selector codebooks on?

**Comment by richgel999** [comment]
Also, note that you can use -global_pal_bits X and -global_mod_bits X to increase the quality when vitual selector codebooks are used. Anything higher than 8 increases quality, but greatly slows down compression because the virtual codebook search is currently exhaustive.

**Comment by richgel999** [comment]
I've verified that if I encode with a larger virtual codebook, the artifacts look much better. 10,10 cuts down the artifacts a lot, but it takes a long time to compress. I'm trying 11,10 to see what happens.

This is definitely an artifact, not a bug.

**Comment by cwoffenden** [comment]
> Is there a particular reason why you are forcing global selector codebooks on?

I was trying the different options shown in the command-line help:
```
basisu -linear -global_sel_pal -no_hybrid_sel_cb -file x.png : Compress a non-sRGB image, use virtual selector codebooks for improved compression (but slower encoding)
```
My choice of test image was created to work well with 4x4 blocks, so the default `basisu` settings were getting the file size down considerably, but when generating mipmaps the size was going up more than expected so I was trying the example options.
