### ISSUE TITLE
ETC2 RG support

### ISSUE THREAD

**Issue by reduz** [BinomialLLC/basis_universal#70]
It is a bit difficult to use BU in a workflow that expects portable RGTC cupport for normalmaps, which are supported fine by both BC5 on desktop and ETC2RG on mobile. If transcoding to EAC is supported, i don't get why this does not work.

**Comment by richgel999** [comment]
I'm working on this now. Looks pretty straightforward.

**Comment by reduz** [comment]
Thanks a lot!

**Comment by richgel999** [comment]
This is done, we are testing it now. Will have it checked in probably tomorrow. We added support for ETC2 EAC R11 and RG11 unsigned.

**Comment by richgel999** [comment]
This is checked in

**Comment by reduz** [comment]
Thanks hugely, will test asap
