### ISSUE TITLE
Crash on compress for file.

### ISSUE THREAD

**Issue by reduz** [BinomialLLC/basis_universal#72]
This file is crashing for me, although it seems to work fine on the standalone compressor. 
I have no idea what I am doing different, but here is the log:

[bucrash.zip](https://github.com/BinomialLLC/basis_universal/files/3660353/bucrash.zip)

```
format: 1 size 128, 128 mipmaps: 0
job_pool::job_pool: 1 total threads
basis_compressor::basis_compressor
basis_compressor::init
basis_compressor::process
basis_compressor::read_source_images
Source image index 0 filename  128x128 has alpha: 0
Any source image has alpha: 0
****** Slice 0: mip 0, alpha_slice: 0, filename: "", original: 128x128 actual: 128x128
Total blocks: 1024, Total macroblocks: 256
Total basis file slices: 1
Slice: 0, alpha: 0, orig width/height: 128x128, width/height: 128x128, first_block: 0, image_index: 0, mip_level: 0, iframe: 0
basis_compressor::validate_texture_type_constraints
basis_compressor::process_frontend
selector_codebook_bpp_est: 0.968750
Auto global selector palette enabled
thirdparty/basis_universal/basisu_frontend.cpp:81: bool basisu::basisu_frontend::init(const basisu::basisu_frontend::params&): Assertion `0' failed.
Aborted (core dumped)
```

**Comment by reduz** [comment]
If I turn this off in the compression parameters, everything seems to work:
```
params.m_no_hybrid_sel_cb = true; 
```

**Comment by richgel999** [comment]
Are you initializing the "m_pSel_codebook" parameter in the basis_compressor_params struct?

I will be providing a C-style API to make using the encoder simpler, BTW. After some other fires are put out first.

**Comment by reduz** [comment]
No, I just left it null as default. Should I initialize it to something?

**Comment by richgel999** [comment]
Yes, you need to pass in a pointer to this:

basist::etc1_global_selector_codebook sel_codebook(basist::g_global_selector_cb_size, basist::g_global_selector_cb);

Like compress_mode() does in basisu_tool.cpp.

The public API will be hiding a lot of these complexities, BTW.

**Comment by reduz** [comment]
This worked perfect, thanks!

**Comment by reduz** [comment]
Is it ok if I share the global selector between instances of the compressor ?
