### ISSUE TITLE
Support for more input image types

### ISSUE THREAD

**Issue by mihaisebea** [BinomialLLC/basis_universal#8]
Hi,

It would be nice to add support for more input image types.
Adding stb_image.h would allow support for tga, hdr and more! 

Cheers,
Mihai

**Comment by richgel999** [comment]
I can't use stb_image.h for PNG (I've had too many customer reports of it being unreliable for that format), but yes we'll bring this in for the other formats.

**Comment by polarathene** [comment]
Would BasisU or UASTC be suitable for compressing HDRI textures(equirectangular or separate faces for cubemap packed into single basis file)?

These can get rather large at higher resolutions, for example [Machine Shop 02 - HDRI Haven](https://hdrihaven.com/hdri/?h=machine_shop_02).

**Comment by richgel999** [comment]
> Would BasisU or UASTC be suitable for compressing HDRI textures(equirectangular or separate faces for cubemap packed into single basis file)?

Not yet, but that is coming at some point. We now support (actively fuzzed) PNG, BMP, TGA, and JPG, which seems to be enough formats for most users. I'm going to close this, but if you have any more suggestions let me know. Thanks!

**Comment by polarathene** [comment]
> Not yet, but that is coming at some point.

> I'm going to close this, but if you have any more suggestions let me know. Thanks!

Is there an issue to track for that, or should I open a new one?
