### ISSUE TITLE
Binary Header for Basis?

### ISSUE THREAD

**Issue by ibgreen** [BinomialLLC/basis_universal#81]
Hi, is there a good way to determine if a binary file is likely to be a basis file based on inspecting the first few bytes?

It doesn't seem like the files start with an ASCII string (like e.g. binary Draco files start with 'DRACO' ASCII in the first 5 bytes) but they do seem to start with the same few characters. 

I didn't find a spec of the format but took a quick peek at the cpp code, looked like the format starts with a `header_size` that I assume is a fixed value for a certain version of the format?

Are there any other bytes at fixed offsets from the header I should look at?

Background - We are working on integrating a basis loader into [loaders.gl](https://github.com/uber-web/loaders.gl/tree/master/modules/basis) and we'd like this loader to participate in our automatic loader selection system.

@georgios-uber @tsherif

**Comment by turol** [comment]
If you figure this out you should also submit it to the "file" program so it can correctly detect basis files. Currently it just shows "data".

**Comment by mosra** [comment]
In [Magnum](https://magnum.graphics) we're checking for a `sB` prefix. It's very short, but at least something ([code for reference](https://github.com/mosra/magnum/blob/c5d08156eaa03867403c32f4b0ee6a56202331e4/src/MagnumPlugins/AnyImageImporter/AnyImageImporter.cpp#L133-L135)). Originally it included also the version info that's right after, but files produced with the current `basisu` tool already have different version than the `kodim20.basis` etc. sample files bundled in this repo.

**Comment by ibgreen** [comment]
> In Magnum we're checking for a sB prefix. 

@mosra Thanks, this unblocks us and we'll do the same. And based on your advice we'll save some time by not trying to implement a stronger heuristic using the the version. 

> If you figure this out you should also submit it to the "file" program so it can correctly detect basis files. Currently it just shows "data".

@turol Good idea! I don't know anything about how to do that, but I suppose that program would have some kind of configuration that would allow for the `sB` header to be mapped to 'image/basis' or something similar...

**Comment by MarkCallow** [comment]
I have a horrid feeling it was intended to be "Bs" but the code as written would only write that if run on a big endian machine.

**Comment by ibgreen** [comment]
@MarkCallow Ha ha, that makes sense. And thanks for clarifying, at least this confirms that `sB` is not a potential non-ASCII string that just happened looked like text, and makes us feel better about relying on it. 

Maybe just bite the bullet and document that the initial type string is `sB` written in big-endian ?

**Comment by mosra** [comment]
So.... it means Basis files produced on little-endian machines are unreadable on big-endian?

**Comment by MarkCallow** [comment]
@mosra. No. On further study, it would be written as  'sB' on a big-endian machine as well. The value is being initialized in an enum (int) as the value 'Bs' but then ints are always be written out in little-endian order. so it comes out as 'sB'. May it is intentional, if weird.
