### ISSUE TITLE
Inconsistent behavior from transcoder

### ISSUE THREAD

**Issue by punto-** [BinomialLLC/basis_universal#82]
Is there any initialization required before I instance a basisu_transcoder and use it? (passing NULL as the constructor parameter) I'm getting broken output from the transcoder when I run it directly (alpha seems to be broken), but if I run the compressor before (even for a 4x4 empty image), the transcoder works fine. I'll gather more details in the next few days, but I thought I'd ask if there's something obvious.

**Comment by c0debon** [comment]
See https://github.com/BinomialLLC/basis_universal/blob/master/transcoder/basisu_transcoder.h#L366

**Comment by punto-** [comment]
ah so there was something obvious that I miss, thanks! :)

**Comment by richgel999** [comment]
Yea - you must call basisu_transcoder_init(). Otherwise a bunch of tables won't be initialized, and the transcoder will do weird things. I'll see if I can make this more obvious.
