### ISSUE TITLE
Build fails on VS2019/Windows Kit 10.0.18362.0 due to `min` def collision

### ISSUE THREAD

**Issue by MarkCallow** [BinomialLLC/basis_universal#85]
Lines 1130 & 1131 in `basisu_enc.cpp` use `std::min`.  `basis_enc.cpp` includes `windows.h`, prepended by a `#define WINDOWS_LEAN_AND_MEAN`, which somewhere includes `minwindef.h`. This defines a macro `min` with which the c preprocessor helpfully replaces the `min` in `std::min` causing the compile to fail.

How can you compile it? Are you using a different version of Windows Kit?

**Comment by MarkCallow** [comment]
`basisu.h` undefs `min` and `max` but the `#include <windows.h>` comes after the basisu header files are included. Not sure whether to fix this by moving the `windows.h` include or adding unders. Please advise.

**Comment by turol** [comment]
Try `#define NOMINMAX` before including `windows.h`.

**Comment by richgel999** [comment]
This is being fixed today, in the UASTC drop coming in a few hours.
Thanks!
