### ISSUE TITLE
ITERATOR_DEBUG_LEVEL madness

### ISSUE THREAD

**Issue by MarkCallow** [BinomialLLC/basis_universal#86]
On Windows `basisu.h` does `#define ITERATOR_DEBUG_LEVEL 1` when compiling for debug. Since VC++'s default level is 2 this leads to a large number of errors from the compiler about an ITERATOR_DEBUG_LEVEL mismatch when you try to use basisu alongside other code.

The comment where this is set says you need to disable iterator debugging or the encoder is unusable. What exactly are the problems it causes? I have defined `BASISU_NO_ITERATOR_DEBUG_LEVEL`  to prevent changing the level and in my very limited experiments the encoder seems to be working okay.

**Comment by richgel999** [comment]
If iterator debugging is enabled, the encoder is just too slow in debug. If you build with BASISU_NO_ITERATOR_DEBUG_LEVEL, this problem should go away.

Considering you're not having problems, I'll make this the default.

**Comment by richgel999** [comment]
For now, we're going to leave the BASISU_NO_ITERATOR_DEBUG_LEVEL macro in, which the user can use. If this is still a problem, let's reopen the bug and I'll just disable it 100%.
