### ISSUE TITLE
Building WASM transcoder on macOS

### ISSUE THREAD

**Issue by donmccurdy** [BinomialLLC/basis_universal#88]
- emscripten 1.38.31
- cmake 3.15.4
- macOS 10.15

From https://github.com/BinomialLLC/basis_universal/tree/master/webgl/transcoder:

```
cd webgl/transcoder/build/
emcmake cmake ../
make
```

<details>

<summary>Gives errors:</summary>

```
/Users/donmccurdy/Documents/Projects/emsdk/emscripten/1.37.22/system/include/libcxx/vector:1031:15: note: in instantiation of
      member function 'std::__2::vector<basist::basisu_slice_info, std::__2::allocator<basist::basisu_slice_info>
      >::__construct_at_end' requested here
        this->__construct_at_end(__n);
              ^
/Users/donmccurdy/Documents/Projects/emsdk/emscripten/1.37.22/system/include/libcxx/vector:2006:15: note: in instantiation of
      member function 'std::__2::vector<basist::basisu_slice_info, std::__2::allocator<basist::basisu_slice_info> >::__append'
      requested here
        this->__append(__sz - __cs);
              ^
/Users/donmccurdy/Documents/Projects/basis_universal/transcoder/basisu_transcoder.cpp:9308:26: note: in instantiation of member
      function 'std::__2::vector<basist::basisu_slice_info, std::__2::allocator<basist::basisu_slice_info> >::resize' requested
      here
                file_info.m_slice_info.resize(total_slices);
                                       ^
note: candidate function not viable: requires 1 argument, but 2 were provided
10 warnings and 16 errors generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
make[2]: *** [CMakeFiles/basis_transcoder.js.dir/Users/donmccurdy/Documents/Projects/basis_universal/transcoder/basisu_transcoder.cpp.o] Error 1
make[1]: *** [CMakeFiles/basis_transcoder.js.dir/all] Error 2
make: *** [all] Error 2
```

</details>

Based on https://github.com/BinomialLLC/basis_universal/pull/12/files I'm guessing the second line of the instructions might need to be altered on macOS:

```
emcmake cmake -DCMAKE_CXX_COMPILER=g++-9 ../
```

But after doing that, `make` exits silently with no output.

**Comment by kenrussell** [comment]
Perhaps @kripken will have an idea what's going wrong?

**Comment by kripken** [comment]
One potential problem is that the description says `emscripten 1.38.31` but the error says `/Users/donmccurdy/Documents/Projects/emsdk/emscripten/1.37.22/`. Those versions are about a year and a half apart, so perhaps the compiler in one is not compatible with the system libraries in the other. Using a single emcc consistently might fix that.

**Comment by donmccurdy** [comment]
I haven't cleaned out my dev environment (not sure how two versions got in there), but I had better luck on another macOS device. Closing the issue, as this seems to just be a local problem. Thanks!
