### ISSUE TITLE
Access to low-level transcoder APIs

### ISSUE THREAD

**Issue by donmccurdy** [BinomialLLC/basis_universal#89]
For projects implementing support for Basis Universal data without relying on a `.basis` wrapper file, e.g. via KTX2, it will be necessary to expose additional features of the low-level transcoder. Currently the WASM transcoder only accepts a `.basis` file as input, for example.

In https://github.com/BinomialLLC/basis_universal/pull/51 some comparable changes are proposed to enable libktx to access the low-level decoder. The PR is specific to libktx, and doesn't expose anything new on the WASM transcoder yet, but is similar in its goals.

I would like to eventually reach a state where multiple libraries can use the low-level transcoder: libktx for complete KTX2 support, a lightweight JS implementation for the web, and perhaps a lightweight native implementation like [tiny_ktx](https://github.com/DeanoC/tiny_ktx). 

@richgel999 would you be open to exposing additional APIs? Or am I asking for the wrong thing, and I should be considering a different high-level API rather than direct access to the low-level transcoder? Open to feedback on how to approach this, thanks.

**Comment by MarkCallow** [comment]
Two notes about PR #51. First there is nothing specific to KTX2 about it. It simply creates a variant of the existing low-level API that does not require a .basis file header pointer. The header is used only to get 2 bits of information about the data. The additional signature passes those bits as explicit parameters in place of the .basis header pointer.

Second I need to update the PR for all the new transcode options. Part of adding those options involved adding parameters to the low-level transcode API. I need to add those same parameters to the new signature.

**Comment by richgel999** [comment]
@richgel999 would you be open to exposing additional APIs? Or am I asking for the wrong thing, and I should be considering a different high-level API rather than direct access to the low-level transcoder? Open to feedback on how to approach this, thanks.

Sorry for the delay. I explicitly wanted to get UASTC support in first, before replying. That's going in today (in hours).

I'm totally open to API changes. Whatever it takes to make KTX2 happy!

**Comment by MarkCallow** [comment]
@richgel999 at least pre-UASTC, KTX2 is happy with the changes proposed in PR #51. However it probably is too low-level for easy or general use. Within libktx I created a `ktxBasisImageTranscoder` which is at roughly the same level as `transcode_image_level` but is independent of container format. This is what I have exposed in `msc_basis_transcoder.js`. You may wish to have something similar in your library.

**Comment by richgel999** [comment]
Low-level transcoding API's are in (for both native and JavaScript).
