### ISSUE TITLE
Issue with quality

### ISSUE THREAD

**Issue by punto-** [BinomialLLC/basis_universal#92]
Hi. We're having an issue with quality, when we compress the same image with etc2comp or squish vs basis universal I get some artifacts that look like poor quality.  Here's an example with etc2comp:

![face](https://user-images.githubusercontent.com/6645309/68984118-3c633680-07ed-11ea-84e7-56474e3085b1.PNG)

And the bu version:
![face_bu](https://user-images.githubusercontent.com/6645309/68984133-48e78f00-07ed-11ea-8556-4ba0cefa67ae.PNG)

It looks like the alpha is losing a lot of quality. What kind of "knobs" do we have to control quality? Are they documented somewhere? I'm using the C++ api from within Godot, and leaving mostly default values in the basisu::basis_compressor_params structure.

Thanks!

**Comment by SBRK** [comment]
In my experience, even with the best quality parameters, I get this kind of bad quality. From what they say, basis universal is designed to produce small file sizes, that are then transcoded to gpu specific compressed formats, so they don't clutter your thread when uploading to the GPU but are still blazingly fast to load.

In my use case, where I have to load a lot of textures - most of them >= 2048x2048 - on a WebGL app, this format is the best tradeoff between fast download, ok quality from a distance, and fast upload to gpu that does not block my javascript thread for 3 seconds at start. I opted for loading basisu textures first, to have a fast initial load, then in a second time load gpu specific version of the texture (pvrtc on ios, s3 on windows desktop, etc) , in higer quality, but with a much higher file size (most of the time over 2MB for a 2k texture). This implies a heavy processing of each texture beforehand, but it seems like the best option right now

**Comment by richgel999** [comment]
Thanks for the feedback. The encoder has a lot of parameters to control quality. I tuned the defaults across a wide range of images/textures, but they could be better. I'm going to recalibrate the defaults. 

Currently we are working on a new codec that has different tradeoffs: much higher quality but less compression performance.

**Comment by richgel999** [comment]
Looks like you aren't using the -q option to increase the codec's quality level.

Here's your image compressed with "basisu -q 255 c:\dev\ti.png" and then transcoded to ETC1. Looks OK to me. Basis Universal is like JPEG - you need to dial up the quality slider to the appropriate desired quality.

REC 709 luma is 50.278 dB:
![ti_unpacked_rgb_ETC1_RGB_0000](https://user-images.githubusercontent.com/6934809/71760003-7ce54500-2e6b-11ea-85ed-d2deb7adcf3d.png)

Here's "basisu  c:\dev\ti2.png -max_endpoints 16000 -max_selectors -16000 -comp_level 3"
REC 709 Luma is 50.354 dB

![ti2_unpacked_rgb_ETC1_RGB_0000](https://user-images.githubusercontent.com/6934809/71760091-bc606100-2e6c-11ea-8269-33bb6040542c.png)

**Comment by punto-** [comment]
What would be the equivalent of these command line options in
the basisu::basis_compressor_params struct? I'm using the library directly.
I tried using  m_quality_level = 255 and it made no difference (set to a
low value it was even worse quality, but 255 gave the same result)

Thanks!
