### ISSUE TITLE
3DFX file signatures likely broken.

### ISSUE THREAD

**Issue by MarkCallow** [BinomialLLC/basis_universal#96]
The 3DFS file signature is initialized by `const uint32_t OUT_FILE_MAGIC = 'TEXC';` for which gcc flags "warning: multichar character constant". I have no idea in what order the compiler would place the characters when initializing OUT_FILE_MAGIC, which is possibly the point of the warning. Whether the T becomes the high-order or low-order byte, who knows?

The value is written out to the file as little endian. What byte sequence is meant to appear in a 3DFS file - TEXC or CXET? Is there any documentation for this file format?

**Comment by richgel999** [comment]
It's an ancient (20 year old) format. It should be "TEXC". I'll fix the code so it's endian safe with no warnings.

**Comment by MarkCallow** [comment]
There's a fix in PR #51.  Here's the [diff](https://github.com/BinomialLLC/basis_universal/pull/51/files#diff-e3aa874a4763ea1d2beeeae3867e5e3b).

**Comment by richgel999** [comment]
Fixed in UASTC build coming today.
